### DISCUSSION TITLE
Migrating from Portainer?

### DISCUSSION THREAD

**Discussion by xela-nosretap** [louislam/dockge#137] [Ask for Help]
I, like a lot of people have been using Portainer for quite a while.

I've just installed Dockge and when I log in I can see a few stacks that say they aren't managed by Dockge, how do get them to be managed by Dockge? Is it just a case of recreating things from withing Dockge?

**Comment by hunkyn** [comment]
Thank you for asking.  Came to here to ask the same. If there is a way to migrate from portainer that would be great.

**Comment by louislam** [comment]
Pretty much manually at this moment:

1. Copy the compose yaml to Dockge with a same stack name and save.
1. Stop and down the stack in Portainer
1. Start the stack via Dockge

**Reply by depasseg** [reply]
This may sound stupid, but will this approach work with volumes?  For some reason, most of my portainer stacks use volumes instead of mount paths.

**Reply by louislam** [reply]
It depends. Mostly yes if you keep the same stack name.

**Reply by HeasHeartfire** [reply]
Basically this for portainer stacks where you can just copy the yaml, but for the rest of the containers that you might not have compose files stored for if you created them using the GUI, you can use a python utility called docker-autocompose to generate said files for you.
It's not pretty because it adds a bunch of redundant parameters that aren't needed (I removed them) but it's better than starting from scratch.

**Reply by epsimatic** [reply]
1. In Portainer, go to «Stack details»
2. *«Detach from Git» if you're managing your stack in Git*
3. Click «Editor», «Copy to clipboard»
4. In Dockge, create a new stack («+Compose»)
5. Delete the generated compose code, paste your own code from the clipboard.
6. Enter the correct «Stack Name» (same as you had in Portainer. Dockge doesn't pick up the stack name from compose yaml)
7. In Portainer, click «Environment variables» → «Advanced mode», «Copy to clipboard»
8. In Dockge, paste the copied text to «.env». Click «Save».

Now, *actually*, the stack is marked Active as Dockge starts managing the stack right away. But let's fully detach it:

1. In Dockge, click «Update» to cut some future downtime.
2. In Portainer, click «Stack» → «Stop this stack»
3. In Dockge, reload the page (the stack is now «inactive»), then click «Start».
4. Do your checks. If all is well, go to Portainer and «Delete this stack»
5. Click «Start» in Dockge again, as Portainer got slightly confused and stopped the stack it isn't actually managing

**Reply by depasseg** [reply]
Will Docker Volumes work this way, or does the data need to be moved?

**Reply by epsimatic** [reply]
Docker volumes stay after you removed the container (check it with `docker volume list`). You *can* delete them after every referencing container is destroyed, but Docker won't remove a volume on its own.

If you remove a container and recreate it, it'll use the same volume with the same data.

**Reply by depasseg** [reply]
Sorry, I mean that if I have a volume being used in Portainer stack, and copy the compose file over to Dockge, will Dockge use the same Volume?

Like in the example below, do I need to do anything special to the speedtest-config and speedtest-db volumes?

```
version: 3.3
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedyadmin
            - DB_PASSWORD=password
            - TZ=America/New_York
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - speedtest-config:/config
        image: ghcr.io/alexjustesen/speedtest-tracker:latest
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: postgres:15
        restart: always
        environment:
            - POSTGRES_DB=speedtest_tracker
            - POSTGRES_USER=pgadmin
            - POSTGRES_PASSWORD=password
        volumes:
            - speedtest-db:/var/lib/postgresql/data
volumes:
  speedtest-config:
  speedtest-db:
```
