### DISCUSSION TITLE
Stack compose file - where is it?

### DISCUSSION THREAD

**Discussion by bearded-papa** [louislam/dockge#165] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

I created a stack with Sonarr, Radarr, prowlarr & Plex but when looking for the config file i couldn't find it. If I make them individual contaiber they are there but not when created as a stack

### 🐻 Dockge Version

1.1.1

### 💻 Operating System and Arch

Debian GNU/Linux 11 (bullseye) arm64

### 🌐 Browser

opera

### 🐋 Docker Version

Docker 24.0.7

**Comment by louislam** [comment]
Show your dockge compose file.

Maybe you missed something.

**Reply by breeegz** [reply]
Obviously I can't speak for Bearded-Papa, but I'm having a similar question.

I've set up a handful of containers with Dockge, love the interface, love the tool..  but I expected that I would have a compose file saved in the /opt/stacks directory.  I can't find them there, I went searching for similar questions/issues and found this one.  If my question doesn't fit in this thread I can try somewhere else.

I suppose that it's possible that the compose files are stored in the dockge.db file, but I thought I would get a compose file in the directory.  Maybe that's the way you set it up, or I have an issue to troubleshoot.

My docker install is a little older on MXLinux (Debian 12 based):
`Docker version 20.10.24+dfsg1, build 297e128`
`docker-compose version 1.29.2, build unknown`

**Reply by breeegz** [reply]
My Dockge compose file is pretty stock:
```
version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
        
      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks
```
