### DISCUSSION TITLE
Add an image, network and volume manager

### DISCUSSION THREAD

**Discussion by stantios** [louislam/dockge#23] [Feature Request]
Description: I came across the project and was amazed by the UI and functionality it has so far. I noticed in the description that this project is maninly focuses on using one compose.yml file for everything and that if you are looking to manage multiple single containers, they should use Portainer or the docker CLI, correct me if I am wrong. I think this project has potential to become something big and even an alternative to portainer.

With that being said, I was hoping if you could incoproate some features from Portainer. For example, an image, networks and volume manager would be incredible to have since I and maybe many people, only use these three tools to manage their whole docker stack without needing any other features from portainer, which makes using Portainer feel bloated since we or I do not need any other tools from their service, but at the end of the day, I am not sure.

This is mainly a feature request to add an image, network and volume manager. Sorry if I went overboard with the description, I spoke what I felt the potential this project had if enough development was done.

**Comment by RandomLegend** [comment]
I'd love to revive this discussion.
I just had a major breakdown of portainer and just decided to not use it anymore. I can do everything in Dockge but one thing is not possible.

To maintain single containers that have to be started via docker run. I'd love to have docker-compose for everything but version 3 of compose doesn't allow the use of macvlan networks and i need one for my adguard so it has a seperate ip adress.

So being able to see / manage non-compose containers and especially networks would be awesome!

**Comment by trythatagain** [comment]
If you're referring to "version: "xx"" then that has been deprecated. I run OMV and did use a "version: 2" yml with a macvlan, I've removed the version line and it all still spins up and works.

I've just tested my yml file with dockge after removing the version line, and it spins up fine, and I can login to, with no problems.

Can I ask why you need to start containers with docker run?

**Reply by RandomLegend** [reply]
Tbh i am no expert on docker networks so maybe i made some errors which lead me to that conclusion.

I run AdGuard via MACVlan because many of the ports it needs open are already used up by other docker services i run on that machine and the IP.

So running it on its own IP adress i can open all these ports without issues.

And i simply couldn't figure out how to do MACVlan with docker-compose... i tried creating a network first and then binding the compose to that one, didn't work. Tried creating a completely new macvlan from inside the compose, didnt work either...

No matter what i tried i couldn't get it working. The only thing was running adguard as docker run, let it crash because the ports are already used up and then manually connecting that container to a preexisting macvlan network and restart it...

**Comment by trythatagain** [comment]
Neither am I :)
Below is what I run in OMV, and what I tested in dockge apart from I use br0, but as long as you have the correct network interface name and ip subnet details, plus correct paths it should work and is a good basic adguard container.
```
######################## AdGuard Home

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
      - 443:443/tcp
      - 443:443/udp 
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 853:853/tcp
      - 3000:80/tcp
 
    volumes:
      - $appdata/adguard/workdir:/opt/adguardhome/work
      - $appdata/adguard/config:/opt/adguardhome/conf

    networks:
      adguard_net: # Your adguard network name
        ipv4_address: 192.168.1.31 # Static address you want
    restart: unless-stopped
    
networks:
  adguard_net:
    driver: macvlan
    driver_opts:
      # your network interface port name
      parent: enp4s0  #yours might be eth0
      #parent: br0 #bridge
    ipam:
     config:
       - subnet: 192.168.1.0/24  # Your currant subnet network
         gateway: 192.168.1.1    # Your gateway for subnet
```
