### DISCUSSION TITLE
Setting up dockge compose properly for an existing setup

### DISCUSSION THREAD

**Discussion by mgrimace** [louislam/dockge#265] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

I have an existing setup with my docker compose files living in /opt/appdata/ (e.g., /opt/appdata/portainer) and everything is on a custom docker network I've called `homelab`. Up front, I know I have to point dockge to /opt/appdata/, but I have some other questions as well -

When creating Dockge, 

1. Can dockge live in its own stack location? For example, /opt/appdata/dockge like the others? 
2. Can/should it be on my existing docker network `homelab`?
3. I have some 'universal' .env files in /opt/appdata that exsiting stacks point to (e.g., .timezone.env, etc.) is that ok?

Here's the compose I tentatively created for dockge, which mirrors my existing compose files (like portainer).

```yaml
version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /opt/appdata:/opt/appdata
    networks:
      - homelab
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/opt/appdata
    security_opt:
      - apparmor:unconfined

networks:
  homelab:
    driver: bridge
    external: true
```

Thanks in advance, I'm new to docker and homelab in general and still learning as I go.

### 🐻 Dockge Version

1.3.2

### 💻 Operating System and Arch

Ubuntu 22.04.03 (Proxmox LXC)

### 🌐 Browser

Safari
