### DISCUSSION TITLE
求助：使用Nginx反向代理之后dockge容器报错

### DISCUSSION THREAD

**Discussion by 20has** [louislam/dockge#314] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

使用Nginx反向代理之后dockge容器报错
```
[root@docker dockge]# docker logs -f dockge
2023-12-20T06:48:11Z [SERVER] INFO: Welcome to dockge!
2023-12-20T06:48:11Z [SERVER] INFO: NODE_ENV: production
2023-12-20T06:48:11Z [SERVER] INFO: Server Type: HTTP
2023-12-20T06:48:11Z [SERVER] INFO: Data Dir: ./data/
2023-12-20T06:48:11Z [DB] INFO: Database Type: sqlite
2023-12-20T06:48:11Z [SERVER] INFO: Connected to the database
2023-12-20T06:48:11Z [SERVER] INFO: Listening on 5001
2023-12-20T06:48:19Z [AUTH] **ERROR**: Origin (https://dock.xxx.com:8888) does not match host (dock.xxx.com), IP: ::ffff:192.168.20.103
2023-12-20T06:48:29Z [AUTH] **ERROR**: Origin (https://dock.xxx.com:8888) does not match host (dock.xxx.com), IP: ::ffff:192.168.20.103
```
### 👟 Reproduction steps

Nginx的配置文件配置如下：
```
[root@Nginx vhost]#
[root@Nginx vhost]# cat dock.xxx.com.conf
server {
    listen 80;
    listen 443 ssl http2;
    server_name  dock.xxx.com;
    #ssl on;
    ssl_certificate      /usr/local/nginx/conf/ssl/*.xxx.com.cer;
    ssl_certificate_key  /usr/local/nginx/conf/ssl/*.xxx.com.key;
    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    location / {
        proxy_pass http://192.168.20.249:5001;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Host $host;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        #proxy_hide_header  Origin;
    }
}
```
dockge容器的yaml文件如下：
```
[root@docker dockge]# cat compose.yaml
version: "3.8"
services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    restart: unless-stopped
    ports:
      - 0.0.0.0:5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Stacks Directory
      #  READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      #  1. FULL path only. No relative path (MUST)
      #  2. Left Stacks Path === Right Stacks Path (MUST)
      - /data/docker/dockge/stacks:/opt/stacks
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/opt/stacks
```

### 👀 Expected behavior

局域网电脑直接访问 http://192.168.20.249:5001 没问题，但是经过nginx反向代理到外部网络访问报错 无法连接到socket服务器。 [Error: websocket error] 重连中…

### 😓 Actual Behavior

![Snipaste_2023-12-20_14-57-28](https://github.com/louislam/dockge/assets/8327740/a99c24f2-e41c-42f3-97f0-fb3fa3b2c939)

### Dockge Version

1.3.5

### 💻 Operating System and Arch

CentOS Linux release 7.5.1804

### 🌐 Browser

chrome 版本 120.0.6099.110（正式版本） （64 位）

### 🐋 Docker Version

docker 24.0.7

### 📝 Relevant log output

局域网电脑直接访问 http://192.168.20.249:5001 没问题，但是经过nginx反向代理到外部网络访问报错 无法连接到socket服务器。 [Error: websocket error] 重连中…
