### DISCUSSION TITLE
Can't open it on mobile

### DISCUSSION THREAD

**Discussion by Samiya321** [louislam/dockge#317] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 👟 Reproduction steps

Typing in a link on my iphone's safari browser and then entering, it doesn't show the page properly, it's blank

### 👀 Expected behavior

Display page content normally

### 😓 Actual Behavior

empty space

### Dockge Version

latest

### 💻 Operating System and Arch

Ubuntu 22.04 x64

### 🌐 Browser

Safari

**Comment by louislam** [comment]
Cannot reproduce, please try https://uptime.kuma.pet

![image](https://github.com/louislam/dockge/assets/1336778/7a417ab8-1623-4119-8d3f-2cbc7d18bd5f)

**Comment by Samiya321** [comment]
> Cannot reproduce, please try https://uptime.kuma.pet
> 
> ![image](https://private-user-images.githubusercontent.com/1336778/292158533-7a417ab8-1623-4119-8d3f-2cbc7d18bd5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTIyNzEsIm5iZiI6MTcwMzE1MTk3MSwicGF0aCI6Ii8xMzM2Nzc4LzI5MjE1ODUzMy03YTQxN2FiOC0xNjIzLTQxMTktOGQzZi0yY2JjN2QxOGJkNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMDk0NjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNiYTRjYjUyZDg5YTY4MDA5MTNiYjIxZDFiYzI2M2Y0MzUwZDcwNjRlNjNhYTNmNTNjZTZhYTUzYjM2Yzc5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KpmF4NmF6UaBwTXO8QECrgRKkAvDHCH48M7FVRQJddg)

I built my own uptime kuma and it opens fine on my phone
But [dockge](https://dockge.samiya.pro) doesn't show up properly on the mobile side

**Comment by louislam** [comment]
iPhone 15 
iOS 17.1

![image](https://github.com/louislam/dockge/assets/1336778/b24ef3c6-cef0-4d55-960c-711e96e8b884)

**Reply by Samiya321** [reply]
I tried it on iPhone 13 / iOS 16.2 and iPhone 13 / iOS 15.1 and it won't open

**Comment by Tooa** [comment]
Hi :wave:,
dockge (docker install, version: 1.3.5) also does **not** load for me on my iPhone 7 with iOS 15.8 (Safari, Firefox iOS 121 build 36782, Chrome iOS 120.0.6099.119). The page "https://uptime.kuma.pet/" works fine on my iPhone with Safari though.

When accessing dockge nothing shows in the log. In contrast, accessing dockge with my notebook shows:

```bash

dockge  | 2023-12-23T22:06:54Z [SERVER] INFO: Socket connected!
dockge  | 2023-12-23T22:06:54Z [AUTH] INFO: Disabled Auth: auto login to admin
```

Any chance to make the dockge server more verbose in the logs? Let me know if you need further information!

#### Appendix

Access via http://<host>:<5001>

```yaml
version: "3.8"

services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/opt/stacks
    ports:
      - "5001:5001"
```
