### DISCUSSION TITLE
How to run dockage on macos?

### DISCUSSION THREAD

**Discussion by andriesfc** [louislam/dockge#329] [Ask for Help] [answered]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

The default instructions do not work for MAC. Does someone has a docker compose file which work on MacOS? (Docker desktop).

### 🐻 Dockge Version

latest

### 💻 Operating System and Arch

MacOS 14.2.1 (23C71) (2.6 GHz 6-Core Intel Core i7)

### 🌐 Browser

Vivaldi

### 🐋 Docker Version

Docker 24.0.7

**Comment by syko9000** [comment]
Without knowing what you mean by "it doesn't work", this works on my mac, basically the defauft with the directories turned into environment vars. In the `.env` file beside the yaml put
```
STACKS=/some/real/directory/stacks
DATA=/some/data/directory/ #optional
```
```
version: "3.8"
services:
  dockge:
    image: louislam/dockge:latest
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DATA:/app/data # optional
      - $STACKS:$STACKS
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=$STACKS
```
