### DISCUSSION TITLE
[HELP] Stacks location and volume mapping

### DISCUSSION THREAD

**Discussion by holocronology** [louislam/dockge#35] [Ask for Help] [answered]
Okay, maybe I'm being dense, but I don't understand what you are trying to say here:

```       # Your stacks directory in the host (The paths inside container must be the same as the host)
      # ⚠️⚠️ If you did it wrong, your data could end up be written into a wrong path.
      # ✔️✔️✔️✔️ CORRECT: - /my-stacks:/my-stacks (Both paths match)
      # ❌❌❌❌ WRONG: - /docker:/my-stacks (Both paths do not match)
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks
```

Where exactly do I put the volume pathing on my host server? 

Is this not accurate and why?
![image](https://github.com/louislam/dockge/assets/65265114/29e95929-c2d0-4873-a86f-f6a9f6c3e634)

**Comment by louislam** [comment, marked as answer]
It is not easy to explain. I find that some people are also confused, I don't know how to make it clear.

I show you more examples here, hope you find the pattern.

CORRECT Examples:
- /volume1/docker/dockge-stacks:/volume1/docker/dockge-stacks
- /a:/a
- /stacks:/stacks
- /my-stacks:/my-stacks
- /opt/stacks:/opt/stacks


INCORRECT Examples:
- /a:/b
- /docker:/opt/stacks
- /volume1/docker/dockge-stacks:/my-stacks
- /stacks:/opt/stacks

Container's Path === Host's Path === MUST

It is a relative path issue of docker-compose which tries to do `docker-compose up` in the container but the docker server is actually in the host.

This stackoverall post explains more in details:
https://stackoverflow.com/questions/63802193/docker-compose-remote-context-path-relative-to-local-machine-instead-of-remote

**Reply by ToshY** [reply]
@louislam I'm not sure why your "INCORRECT Examples" denote that the host directory cannot be different from the container directory. 

I have the following directory structure:
```text
/var/tools/collection/
├── dockge/
│   └── .env
│   └── compose.yaml
└── kuma/
    └── compose.yaml
```

And use the following `compose.yaml` for `dockge`.

<details><summary><code>/var/tools/collection/dockge/compose.yaml</code></summary>

```yaml
version: '3.9'

x-restart: &restart-always
  restart: always

services:
  dockge:
    image: louislam/dockge:${DOCKGE_IMAGE_VERSION}
    <<: [*restart-always]
    security_opt:
      - no-new-privileges:true
    environment:
      DOCKGE_STACKS_DIR: ${DOCKGE_STACKS_DIR_CONTAINER:-/opt/stacks}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockge:/app/data
      - ${DOCKGE_STACKS_DIR_HOST:-/opt/stacks}:${DOCKGE_STACKS_DIR_CONTAINER:-/opt/stacks}
    networks:
      - dockge
      - proxy

volumes:
  dockge:
    driver: local

networks:
  dockge:
    driver: bridge
  proxy:
    external: true
```

</details> 

Having the following `.env` variables defined for `dockge`.

<details><summary><code>/var/tools/collection/dockge/.env</code></summary>

```dotenv
DOCKGE_IMAGE_VERSION="1"
DOCKGE_STACKS_DIR_HOST="../" # resolves to "/var/tools/collection" on host
DOCKGE_STACKS_DIR_CONTAINER=
```

</details> 

This works fine and mounts the stacks in `/var/tools/collection` from host to `/opt/stacks` in the container.
