### DISCUSSION TITLE
Support for SSO and User Roles

### DISCUSSION THREAD

**Discussion by lmarschall** [louislam/dockge#367] [Feature Request]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Other

### 🔖 Feature description

Would love to use AzureAD for example to log in to dockge and be able to have user roles according to the accounts.

### ✔️ Solution

Adding SSO Support with User Role Features.

**Comment by bradfordjns** [comment]
This is possible using a reverse proxy such as Traefik and middleware such as Authentik that would be added to the docker-compose.yml of the Dockge container, please see below for the example config. However I would love to see this base able to use Keycloak.

```yml

version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt:/opt
    environment:
      - DOCKGE_STACKS_DIR=/opt
    networks:
      - ${traefik_proxy_network}
    labels:
 #add this to any container you want to use the Traefik web proxy
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.entrypoints=http"
      - traefik.http.routers.dockge.rule=Host(`${dockge_external_url}`)
      - "traefik.http.middlewares.dockge-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dockge.middlewares=dockge-https-redirect"
      - "traefik.http.routers.dockge-secure.entrypoints=https"
      - traefik.http.routers.dockge-secure.rule=Host(`${dockge_external_url}`)
      - "traefik.http.routers.dockge-secure.tls=true"
      - "traefik.http.routers.dockge-secure.service=dockge"
      - traefik.http.services.dockge.loadbalancer.server.port=${dockge_port}
      - traefik.docker.network=proxy
      - "traefik.http.routers.dockge-secure.middlewares=middlewares-authentik@file" #add this to any container you want to use the Authentik middleware

networks:
  proxy:
    external: true

```
