### DISCUSSION TITLE
Piped - error trying to deploy

### DISCUSSION THREAD

**Discussion by di5cord20** [louislam/dockge#386] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

Has anyone managed to get Piped (https://github.com/TeamPiped/Piped) working in Dockge?  I'm getting the below error.

Here's my compose:
```
version: "3.8"
services:
  pipedfrontend:
    image: 1337kavin/piped-frontend:latest
    restart: unless-stopped
    depends_on:
      - piped
    container_name: piped-frontend
    entrypoint: ash -c 'sed -i s/pipedapi.kavin.rocks/pipedapi.mydomain.xyz/g
      /usr/share/nginx/html/assets/* && /docker-entrypoint.sh && nginx -g
      "daemon off;"'
  piped-proxy:
    image: 1337kavin/piped-proxy:latest
    restart: unless-stopped
    environment:
      - UDS=1
    volumes:
      - piped-proxy:/app/socket
    container_name: piped-proxy
  piped:
    image: 1337kavin/piped:latest
    restart: unless-stopped
    volumes:
      - ./config/config.properties:/app/config.properties:ro
    depends_on:
      - postgres
    container_name: piped-backend
  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - 8888:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/pipedapi.conf:/etc/nginx/conf.d/pipedapi.conf
      - ./config/pipedproxy.conf:/etc/nginx/conf.d/pipedproxy.conf
      - ./config/pipedfrontend.conf:/etc/nginx/conf.d/pipedfrontend.conf
      - ./config/ytproxy.conf:/etc/nginx/snippets/ytproxy.conf
      - piped-proxy:/var/run/ytproxy
    container_name: nginx
    depends_on:
      - piped
      - piped-proxy
      - pipedfrontend
  #        labels:
  #            - "traefik.enable=true"
  #            - "traefik.http.routers.piped.rule=Host(`piped.mydomain.xyz`, `pipedapi.mydomain.xyz`, `pipedproxy.mydomain.xyz`)"
  #            - "traefik.http.routers.piped.entrypoints=websecure"
  #            - "traefik.http.services.piped.loadbalancer.server.port=8080"
  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=piped
      - POSTGRES_USER=piped
      - POSTGRES_PASSWORD=changeme
    container_name: postgres
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    container_name: watchtower
    command: piped-frontend piped-backend piped-proxy varnish nginx postgres watchtower
volumes:
  piped-proxy: null
networks: {}
```

### 📝 Error Message(s) or Log

Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/opt/stacks/piped/config/nginx.conf" to rootfs at "/etc/nginx/nginx.conf": mount /opt/stacks/piped/config/nginx.conf:/etc/nginx/nginx.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

### 🐻 Dockge Version

1.4.1

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

Google Chrome
