### DISCUSSION TITLE
Help with running Dockge on Synology NAS - DSM 7.2

### DISCUSSION THREAD

**Discussion by QuickSwitchLK** [louislam/dockge#395] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

Can anyone provide me with information on the following?
I currently have Docker (Container Manager) running on a Synology NAS with DSM 7.2.

I have this working well with many Docker containers running, all set up in directories with a docker-compose.yml file in each.

I currently use Portianer but would like to start using Dockge.

I use Portainer to pull updates and recreate the container in one action and to see what is hidden by the Synology "Container Manager" UI, and again this is working.

If I go to Stacks in Portainer I see "Limited" as all of my creation happens in Synology "Container Manager" and I don't have any problems that come from this.

My question is can I run Dockge in this environment and point directories to existing containers and docker-compose.yml files?
I don't want to start a new container location or stop Container Manager from working.

My directory structure looks like this...

volume1/docker/uptimekuma
volume1/docker/uptimekuma/docker-compose.yml
volume1/docker/uptimekuma/data/ ( Persistent data directory set via volumes: )

volume1/docker/sonarr
volume1/docker/sonarr/docker-compose.yml
volume1/docker/sonarr/config/ ( Persistent data directory set via volumes: )

ect...

I want to add Dockge as volume1/docker/dockge with the following docker-compose.yml

```
version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5999:5001
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
⚠️    - '/volume1/docker/dockge/data:/app/data' ⚠️
⚠️    - '/volume1/docker:/volume1/docker' ⚠️
    environment:
      # Tell Dockge where to find the stacks
⚠️    - DOCKGE_STACKS_DIR=/volume1/docker ⚠️
```

Will this work with all of my previously created containers and still allow me to keep Container Manager working as is?

I usually have a crack and work it out myself, but I have too many containers set up and working perfectly now for this to be an "Oh crap!" data loss moment.

Thanks for any help / advice / already have this working with no data loss 😉 comments. QuickSwitchLK.

### 🐻 Dockge Version

1.4.2

### 💻 Operating System and Arch

Synology NAS - DMS 7.2

### 🌐 Browser

Firefox 121.0.1 (64-bit)

### 🐋 Docker Version

Docker 20.10.23-1437 (Package Center)
