### DISCUSSION TITLE
Cannot start a container with "sysctls", "net.ipv4.ping_group_range="

### DISCUSSION THREAD

**Discussion by eiacub** [louislam/dockge#434] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

Hi,

I am trying to start an Twingate agent using dockge and cannot. I get the following error: "Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: write /proc/sys/net/ipv4/ping_group_range: invalid argument: unknown"

the compose.yml file is:

```
version: "3.3"
services:
  connector:
    sysctls:
      - net.ipv4.ping_group_range="0 2148583647"
    environment:
      - TWINGATE_NETWORK=REDACTED
      - TWINGATE_ACCESS_TOKEN=REDACTED
      - TWINGATE_REFRESH_TOKEN=REDACTED
      - TWINGATE_LABEL_HOSTNAME=`hostname`
    container_name: twingate-some-thing
    restart: unless-stopped
    pull_policy: always
    image: twingate/connector:1
networks: {}
```

can you please help? of course, the container is working if I start it outside gockge.

### 📝 Error Message(s) or Log

[+] Running 1/1
 ✔ connector Pulled                                                                                 1.3s 
[+] Running 0/1
 ⠴ Container twingate-copper-ara  Starting                                                          0.5s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: write /proc/sys/net/ipv4/ping_group_range: invalid argument: unknown

### 🐻 Dockge Version

1.4.2

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

any

### 🐋 Docker Version

Docker version 25.0.3
