### DISCUSSION TITLE
Attach existing volumes from migrated server

### DISCUSSION THREAD

**Discussion by p10tyr** [louislam/dockge#484] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

I moved all my docker volumes from old server to new server.
I am new to dckge, ok - I want to create `uptime-kuma` using an existing volume - I created the volume using `docker volume`

I get the error 
`service refers to undefined volume invalid compose project`

I have to manually update the compose file to look like this before it starts.

```
version: "3.8"
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma:/app/data
volumes: <<
  uptime-kuma: <<
      external: true <<
networks:
  dockge_default:
    external: true
```

Maybe a UI option, like with networks on the right side to handle like volumes you add. you can change the check box to "external"?
Or have a drop down in the volumes bit to select existing volumes 

I know this is the case.. usually you just want to bind to a directory that is easy for backup I guess.. but im migrating this is easiest option.

### 📝 Error Message(s) or Log

service refers to undefined volume invalid compose project

### 🐻 Dockge Version

there is no version displayed on the UI how am i supposed to know?

### 💻 Operating System and Arch

debian LTS

### 🌐 Browser

Edge

### 🐋 Docker Version

Latest

### 🟩 NodeJS Version

na
