### DISCUSSION TITLE
cannot run

### DISCUSSION THREAD

**Discussion by helloxz** [louislam/dockge#498] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

I used docker compose to deploy dockge, but it couldn't be started normally. Check the container log as follows

### 📝 Error Message(s) or Log

```
bash: line 1:     7 Aborted                 (core dumped) node ./extra/clean-tsx-tmp.js
node[7]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb83f50 node::Abort() [node]
 2: 0xb83fce  [node]
 3: 0xbf14ee  [node]
 4: 0xbf15d1 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xb41ed3 node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
 6: 0xb4256b node::Start(int, char**) [node]
 7: 0x7f89313d01ca  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f89313d0285 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xac1fee _start [node]
bash: line 1:     7 Aborted                 (core dumped) node ./extra/clean-tsx-tmp.js
```

### 🐻 Dockge Version

1.4.2

### 💻 Operating System and Arch

CentOS 7

### 🌐 Browser

Chrome

### 🐋 Docker Version

Docker version 19.03.9

### 🟩 NodeJS Version

none

**Comment by helloxz** [comment]
@louislam Can you help me?

**Comment by nathan815** [comment]
Please share what your docker-compose file looks like.

**Reply by helloxz** [reply]
```yml
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /data/apps:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
```

**Comment by JinbaIttai** [comment]
> 🐋 Docker Version
> Docker version 19.03.9

> Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed. 1: 0xb83f50 node::Abort() [node]

It's a common error seen when running node based containers on old CentOS provided Docker.

You need at least Docker v20 (see https://github.com/louislam/dockge) 

See https://docs.docker.com/engine/install/centos/

Also, please carefully read the comments in the provided [Docker Compose File](https://github.com/louislam/dockge/blob/master/compose.yaml) again

> # Stacks Directory
>      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
>      # ⚠️ 1. FULL path only. No relative path (MUST)
>      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)

if you change the /opt/stacks directory you need to change it in all three places.

ie:

```yaml
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /data/apps:/data/apps
    environment:
      - DOCKGE_STACKS_DIR=/data/apps
```
