### DISCUSSION TITLE
Love this tool! question about scanning existing running containers

### DISCUSSION THREAD

**Discussion by wireddude** [louislam/dockge#50] [General]
I love uptime-kuma and this tool is awesome too! I already have 3 containers running on my test server, is there any way to import them into dockge? Do I need to expose the docker docket when starting up so they can be seen? I'd like to have this be aware of my uptime-kuma instance running on the same machine and then fire it up though dockge so I can control/upgrade from here with the yaml file moving foward. Is there an easy way to do this without destroying the existing uptime-kuma container, recreating yaml and firing it up again? Will my directories stay where they are and any data lost from the volumes if I do this?

**Comment by wireddude** [comment]
I couldn't wait and took a stab at this ;)  but it didn't work how I expected.

On the command line and/or portioner:
```
docker stop uptime-kuma
docker rm uptime-kuma
```

Then used the dockge converter to convert this to a compose file:
`docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data -v /var/run/docker.sock:/var/run/docker.sock --name uptime-kuma louislam/uptime-kuma:1`

output compose.yaml file:
```
version: "3.3"
services:
  uptime-kuma:
    restart: always
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
volumes:
  uptime-kuma: {}
networks: {}
```

When I started it up, it asked me to create a new password so I new it wasn't seeing the original volume. I thought perhaps it was the network, but I couldn't seem to start on the same network so I exported the json from original instance and imported into the new dockge instance. I still have my original volume I'd be curious if there is a better way.

**Reply by louislam** [reply]
Since your volume `uptime-kuma` was created outside of the stack, you need to:

Method 1:
Point to external `uptime-kuma` volume

```yaml
volumes:
  uptime-kuma:
    external: true
```

Method 2: Move your data to this stack's volume

From: /var/lib/docker/volumes/uptime-kuma
To: /var/lib/docker/volumes/<STACK_NAME>-uptime-kuma
