### DISCUSSION TITLE
Can't create login account

### DISCUSSION THREAD

**Discussion by ZuluPilgrim** [louislam/dockge#525] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

After entering username and password, and then clicking create, nothing happens. The page stays at the create screen and the button no longer is clickable.

I used the interactive screen to create the docker compose
```
version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /home/sysadmin/docker:/home/sysadmin/docker
    environment:
      # Tell Dockge where to find the stacks

```

### 📝 Error Message(s) or Log

2024-05-17T22:46:08Z [SERVER] INFO: Welcome to dockge!
2024-05-17T22:46:08Z [SERVER] INFO: NODE_ENV: production
2024-05-17T22:46:08Z [SERVER] INFO: Server Type: HTTP
2024-05-17T22:46:08Z [SERVER] INFO: Data Dir: ./data/
2024-05-17T22:46:08Z [DB] WARN: ENOENT: no such file or directory, open 'data/db-config.json'
2024-05-17T22:46:08Z [DB] INFO: Database Type: sqlite
2024-05-17T22:46:08Z [SERVER] INFO: Connected to the database
2024-05-17T22:46:09Z [SERVER] INFO: JWT secret is not found, generate one.
2024-05-17T22:46:09Z [SERVER] INFO: Stored JWT secret into database
2024-05-17T22:46:09Z [SERVER] INFO: No user, need setup
2024-05-17T22:46:09Z [SERVER] INFO: Listening on 5001
2024-05-17T22:46:26Z [AUTH] INFO: Origin is not set, IP: ::ffff:192.168.10.5
2024-05-17T22:46:26Z [SERVER] INFO: Socket connected (direct)
2024-05-17T22:46:26Z [SERVER] INFO: Redirect to setup page
2024-05-17T22:47:11Z [SERVER] INFO: Socket disconnected!
2024-05-17T22:47:13Z [AUTH] INFO: Origin is not set, IP: ::ffff:192.168.10.5
2024-05-17T22:47:13Z [SERVER] INFO: Socket connected (direct)
2024-05-17T22:47:13Z [SERVER] INFO: Redirect to setup page
2024-05-17T22:47:36Z [AUTH] INFO: Origin is not set, IP: ::ffff:192.168.10.5
2024-05-17T22:47:36Z [SERVER] INFO: Socket connected (direct)
2024-05-17T22:47:36Z [SERVER] INFO: Redirect to setup page
2024-05-17T22:47:58Z [SERVER] INFO: Socket disconnected!
2024-05-17T22:48:21Z [SERVER] INFO: Socket disconnected!
2024-05-17T22:48:22Z [AUTH] INFO: Origin is not set, IP: ::ffff:192.168.10.5
2024-05-17T22:48:22Z [SERVER] INFO: Socket connected (direct)
2024-05-17T22:48:22Z [SERVER] INFO: Redirect to setup page
2024-05-17T22:49:07Z [SERVER] INFO: Socket disconnected!
2024-05-17T22:49:31Z [AUTH] INFO: Origin is not set, IP: ::ffff:192.168.10.5
2024-05-17T22:49:31Z [SERVER] INFO: Socket connected (direct)
2024-05-17T22:49:31Z [SERVER] INFO: Redirect to setup page
2024-05-17T22:50:01Z [SERVER] INFO: Socket disconnected!
2024-05-17T22:50:17Z [AUTH] INFO: Origin is not set, IP: ::ffff:192.168.10.5
2024-05-17T22:50:17Z [SERVER] INFO: Socket connected (direct)
2024-05-17T22:50:17Z [SERVER] INFO: Redirect to setup page

### 🐻 Dockge Version

14-1.4.2

### 💻 Operating System and Arch

Ubuntu 22.04.4

### 🌐 Browser

Firefox 125.0.2.

### 🐋 Docker Version

25.0.4

### 🟩 NodeJS Version

N/A

**Comment by JinbaIttai** [comment]
The last line in your compose file is

```yaml
      # Tell Dockge where is your stacks directory
```

but you're missing the line directly after that, which means Dockge doesn't know where it lives.

Please add the following to your compose.yaml and try again

```yaml
   - DOCKGE_STACKS_DIR=/home/sysadmin/docker
```

Note: there should be two spaces at the start of that line, because it's a parameter to the `environment:` label two lines above.

**Comment by ZuluPilgrim** [comment]
Sorry I cut the line off when I pasted it in.. it is there

```
version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writin>
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /home/sysadmin/docker:/home/sysadmin/docker
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/home/sysadmin/docker

```
