### DISCUSSION TITLE
Auto generate ports

### DISCUSSION THREAD

**Discussion by vishalkadam47** [louislam/dockge#53] [Feature Request]
Would it be possible to Auto generate ports to avoid conflicts

**Comment by holocronology** [comment]
Or, at least display a list of current alloted ports, ala the way that Unraid does.

**Comment by nett00n** [comment]
I can give some clarifications here:

When you annotate a port in compose like `3000` and not like `3000:3000`, docker machine allocate you some random port. It would be great to be able to see it with no additional work

```yaml
version: "3.3"
services:
  fenrus:
    container_name: Fenrus
    environment:
      - TZ=Pacific/Auckland
    ports:
      - 3000
    volumes:
      - /data/fenrus:/app/data
    restart: unless-stopped
    image: revenz/fenrus:latest
networks: {}
```

```text
root@9f1cd3e36c18:/opt/stacks# docker ps | grep fenrus
70c3d3943ffc   revenz/fenrus:latest                     "/app/docker-entrypo…"   About a minute ago   Up About a minute         0.0.0.0:32770->3000/tcp                                            Fenrus
```
