### DISCUSSION TITLE
How do you actually migrate to Dockage?

### DISCUSSION THREAD

**Discussion by RyanHakurei** [louislam/dockge#557] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

Hey all, how am I actually supposed to migrate Compose files over to Dockage? No matter what, whether I scan Compose files or copy and paste into Dockage, Dockage always throws errors. It either throws errors about the yaml file itself, or even if it accepts the file it always says "additional property is not allowed" referring to the container name (the actual name of the container, not the 
"pretty" name defined by `container_name`). My Compose file works perfectly with Docker Compose via the command line so there are zero errors in the file itself or else Compose would complain, and I am really trying to make this setup easily manageable for those who may not be as comfortable with the command line as me.

Here is a snippet of my Compose file. This is the stack I am trying to create (as I gather from this project the idea is that each app runs in its own stack, so I have Nginx here and its database as one stack). Yes, I did edit the passwords and users so they will not match, and I do have networks defined.

```
    nginx-db:
        container_name: Nginx-Proxy-DB
        restart: always
        volumes:
            - /opt/Containers/nginx-db/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=database
            - MYSQL_USER=itsauser
            - MYSQL_PASSWORD=passowrd1
            - PUID=1000
            - PGID=1000
        networks:
            nginx-internal:
                ipv4_address: 10.220.1.2
        image: yobasystems/alpine-mariadb

    nginx-app:
        container_name: Nginx-Proxy-App
        restart: always
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - /opt/Containers/nginx-app/data:/data
        tmpfs:
            - /etc/letsencrypt:noexec,nosuid,nodev,size=20M,uid=1000,gid=1000
        environment:
            - PGID=1000
            - PUID=1000
            - TZ=America/New_York
            - DB_MYSQL_HOST=nginx-db
            - DB_MYSQL_PORT=3306
            - DB_MYSQL_USER=lol no
            - DB_MYSQL_PASSWORD=nope.avi
            - DB_MYSQL_NAME=Its-something
        depends_on:
            - nginx-db
        networks:
            nginx-internal:
                ipv4_address: 10.220.1.3
            nginx-http:
                ipv4_address: 10.220.2.2
            default:
        image: jc21/nginx-proxy-manager:latest

networks:
    nginx-internal:
        name: Nginx-Internal
        ipam:
         driver: default
         config:
           - subnet: 10.220.1.0/24
             gateway: 10.220.1.1
    nginx-http:
        name: Nginx-http
        ipam:
         config:
           - subnet: 10.220.2.0/24
             gateway: 10.220.2.1
```

### 📝 Error Message(s) or Log

validating /opt/Containers/stacks/nginx-proxy/compose.yaml: (root) Additional property nginx-db is not allowed
validating /opt/Containers/stacks/nginx-proxy/compose.yaml: (root) Additional property nginx-app is not allowed

### 🐻 Dockge Version

1.4.2

### 💻 Operating System and Arch

AlmaLinux 9.4

### 🌐 Browser

Vivaldi 

### 🐋 Docker Version

26.1.4, build 5650f9b
