### DISCUSSION TITLE
Are .env files supported?

### DISCUSSION THREAD

**Discussion by Dima-Kal** [louislam/dockge#57] [Ask for Help]
Im using .env file for all my stacks, and all of them report missing vars:

WARN[0000] The "DOCKER_STORAGE_PATH" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_NETWORK" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SERVER_DOMAIN" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SERVER_DOMAIN" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_NETWORK" variable is not set. Defaulting to a blank string.

**Comment by ToshY** [comment]
I'm also using `.env` for my existing stacks in dockge without any console warnings when starting the stack. How does your `compose.yaml` for your stack look like then?

**Comment by Dima-Kal** [comment]
For example:

```
  authelia:
    image: authelia/authelia:v4.38.0-beta2
    container_name: authelia
    user: "1000"
    volumes:
      #- ./authelia:/config
      - "./configs/authelia/authelia-config.yml:/config/configuration.yml:ro"
      - "./configs/authelia/authelia-users-database.yml:/config/users_database.yml:ro"
      - "./configs/authelia/private.pem:/config/private.pem:ro"
      - "${DOCKER_STORAGE_PATH}/network/authelia/config:/config"
    networks:
      - ${DOCKER_NETWORK}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`authelia.${SERVER_DOMAIN}`, `auth.${SERVER_DOMAIN}`)"
     ```

**Comment by louislam** [comment]
Where did you put your .env file?

As long as you set the stacks path correctly, dockge's deploy/start are just like a normal "docker compose up".

Correct stacks path related discussion:
https://github.com/louislam/dockge/discussions/26

**Comment by OJ7** [comment]
Does Dockge support _editing_ .env files through the UI?

**Reply by JuryBlurry** [reply]
Not currently

**Reply by syko9000** [reply]
I spent a couple days and added .env file editing to my fork. I'm not 100% sold on the UI placement but it works as expected. Here is a silly example. The prismjs highlighting was the most complicated bit. After some discussion (per the contribution rules) I can PR it in if there is interest.

<img width="479" alt="Screenshot 2023-11-30 at 3 20 27 PM" src="https://github.com/louislam/dockge/assets/193088/5f43179a-5c28-499a-8e3d-351f79d8b729">

**Reply by louislam** [reply]
@syko9000 Looks promising. Feel free to create a pull request for this.

**Reply by trythatagain** [reply]
I assume this is adding a .env file in the same place as the compose.yml for whatever container you're creating? If this gets included, could this also be used to setup a 'global.env' file, say a separate button next to the 'Home' button?
Especially if a 0 byte 'global.env' file is created when spinning up Dockge and included in the 'docker compose -up' command.

**Reply by syko9000** [reply]
Yes, this is just the .env beside the .yml. I have no design decisions but I think that global.env would be its own "tab" in the settings pages. Not sure where the file would be stored (just in stacks maybe? so compose files would just ../global.env. Adding it to the docker compose up command doesn't seem that complicated either. I'm be happy to put that together, if @louislam wants it.

**Reply by almereyda** [reply]
What kind of data would you put in a global environment file? I'm unsure I understand how this could be used.

**Reply by trythatagain** [reply]
I use a global .env file as I use OMV, and OMV recommends using the full path for directories in compose files, I have used sym-links, but  as I can use a global .env file I prefer the ,env file.
Especially useful when spinning up media containers.

for example -
APPDATA="/srv/dev-disk-by-uuid-2b9b3914-0f0d-4737-9638-f6740d0ddf18/appdata"
TZ="Europe/London"
PUID=1000
PGID=100    
=======================
Then in my compose.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $APPDATA/dockge:/app/data
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ

**Reply by EdgarM73** [reply]
Hi,

my main reason for an global .env file:

I have several compose files and i am using a ip range for all of my containers.

there for i have this design:

...
    networks:
      dockervlan:
        ipv4_address: ${IP_IOBROKER}
...

and the ip adresses for all of my containers are in one global .env file which is beeing sources for my linux user.

and my global .env looks like this:
...
IP_IOBROKER='172.23.2.1'
IP_DECONZ='172.23.2.2'
IP_GITEA='172.23.2.3'
IP_FS='172.23.2.4'
IP_GRAFANA='172.23.2.5'
IP_WARDEN='172.23.2.10'
IP_DIYHUE='172.23.2.197'
IP_PHPMYADMIN='172.23.2.6'
IP_SEAFILE='172.23.2.7'
IP_GLANCES='172.23.2.8'
IP_DOZZLE='172.23.2.9'
IP_PAPERLESS='172.23.2.20'
IP_WATCHTOWER='172.23.2.21'
IP_CODE='172.23.2.22'
IP_BOOKSTACK='172.23.2.23'
IP_PGADMIN='172.23.2.26'
...

It would be even better, if this could be done in dockge.

regards
E

**Comment by Dima-Kal** [comment]
> Where did you put your .env file?
> 
> As long as you set the stacks path correctly, dockge's deploy/start are just like a normal "docker compose up".
> 
> Correct stacks path related discussion: #26

Heres an example for one of the stacks folder:

![image](https://github.com/louislam/dockge/assets/39248175/b62cd7c4-7a48-4b5a-88d5-fa7d40261a54)

**Reply by louislam** [reply]
Can you show your Dockge config?

**Reply by louislam** [reply]
```yaml
      - /opt/stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
```

You have to make sure THREE paths are match, otherwise, it cannot read the .env file.

**Reply by Dima-Kal** [reply]
```  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    networks:
      - ${DOCKER_NETWORK}
    dns:
      - ${PIHOLE_DNS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_STORAGE_PATH}/dockge/data:/app/data
        
      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Your stacks directory in the host (The paths inside container must be the same as the host)
      # ⚠️⚠️ If you did it wrong, your data could end up be written into a wrong path.
      # ✔️✔️✔️✔️ CORRECT: - /my-stacks:/my-stacks (Both paths match)
      # ❌❌❌❌ WRONG: - /docker:/my-stacks (Both paths do not match)
      - ./stacks:/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/stacks
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.rule=Host(`dockge.${SERVER_DOMAIN}`)"
      - "traefik.http.services.dockge.loadbalancer.server.port=5001" ```

**Reply by louislam** [reply]
```
- ./stacks:/stacks
```

That's the problem. It do not match.

**Reply by Dima-Kal** [reply]
Doesn't that mean it shouldn't work at all?

**Reply by louislam** [reply]
Dockge is very special, I can never explain it clearly. I can fix it for you.

What is the full path of `./stacks`?

**Reply by Dima-Kal** [reply]
The configuration should not rely on full path,
I have a main compose file that contains all things that manage the docker stacks (Portainer, Watchtower, Dockge..) and the stacks folder of the containers, like this:

![image](https://github.com/louislam/dockge/assets/39248175/87430952-fbd9-46e5-91b2-8e8d2f405f6a)

**Reply by louislam** [reply]
If you don't provide the full path to Dockge, Dockge don't know your actual path on your host. 

Why Portainer don't need this? Because they kidnapped your compose files, you have no control of that.

**Reply by Dima-Kal** [reply]
I've tried to create the following addition to my script, to create an ENV variable for root path and pass it to the compose, but that didn't work:

```
rootDir=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
echo "Root dir is ${rootDir}"

sed -i "s|^DOCKER_STACK_PATH=.*|DOCKER_STACK_PATH=$rootDir|" $rootDir/.env
```

The env file is updated correctly:

```
DOCKER_STACK_PATH=/home/dimak/selfhost
```

```
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    env_file: .env
    networks:
      - ${DOCKER_NETWORK}
    dns:
      - ${PIHOLE_DNS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_STORAGE_PATH}/dockge/data:/app/data

      - ${DOCKER_STACK_PATH}:${DOCKER_STACK_PATH}
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=${DOCKER_STACK_PATH}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.rule=Host(`dockge.${SERVER_DOMAIN}`)"
      - "traefik.http.services.dockge.loadbalancer.server.port=5001"
  ```
used this to bring up the stack:
`docker compose --env-file .env up -d`

but now dockge is broken, no working stacks, and if i echo:
docker exec -it selfhost-dockge-1 echo ${DOCKGE_STACKS_DIR}
it returns empty value
