### DISCUSSION TITLE
One or two containers crash at irregular intervals and don't go back up automatically

### DISCUSSION THREAD

**Discussion by ghost** [louislam/dockge#572] [Ask for Help] [answered]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

Hi all,

This is happening on Debian 12 Minimal running latest Docker/Compose on a HP ProDesk 600 G4 Mini MediaServer with Intel i5-8500T, Intel UHD Graphics 630 and 16GB of RAM.

The host machine has 2 NVME drives, one has the OS and all containers, the other has the media I want containers to access, and an Unraid share on a different machine is also mounted, which is another media source.

All my stacks are created through Dockge (but problem persists even when creating the container outside Dockge).
This happens for example with the official Jellyfin container. The containers crash without any obvious reason. Has happened for example with Jellyfin while the Jellyfin server is not accessed by any client, and I also experienced crashes while playing media. All media plays fine when the container is up. Furthermore, even though all containers are set to "restart: unless-stopped", they do not restart.

I have removed the containers fully and rebuilt them 5-6 times (after clearing any folders, settings, downloaded images, volumes, networks etc), and the same thing keeps happening. No issues with high temperatures on the host machine, plenty of disk space available (over 200 GB) on both NVME drives, all other containers working fine and never crashing.

Any ideas what I am doing wrong please? Are there any containers that are known not to play well with Dockge?

### 📝 Error Message(s) or Log

No error messages are shown, other than the containers stopping and not restarting.

### 🐻 Dockge Version

1.4.2

### 💻 Operating System and Arch

Debian 12 Minimal

### 🌐 Browser

None, the machine is headless. I am accessing Dockge with Firefox or Chrome from a different machine.

### 🐋 Docker Version

Docker version 27.1.0, build 6312585 and Docker Compose version v2.29.0

### 🟩 NodeJS Version

Not running NodeJS

**Comment by trythatagain** [comment]
Probably going to see the compose.yml file at least.

**Comment by ghost** [comment]
/services:
  jellyfin:
    container_name: {redacted by mod}1_jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    network_mode: host
    group_add:
      - "105" # In terminal run the command and put the number here >>> getent group render | cut -d: -f3
    volumes:
      - /home/user/docker_backup/jellyfin/config:/config
      - /home/user/docker_backup/jellyfin/cache:/cache
      - type: bind
        source: /mnt/2TB_DISK/{redacted by mod}/watch_or_save
        target: /watch_or_save
        read_only: true
      - type: bind
        source: /mnt/2TB_DISK/HOME_VIDEOS
        target: /HOME_VIDEOS
        read_only: true
      - type: bind
        source: /mnt/UNRAID_MEDIA/ANIMATED
        target: /ANIMATED
        read_only: true
      - type: bind
        source: /mnt/UNRAID_MEDIA/DOCUMENTARIES
        target: /DOCUMENTARIES
        read_only: true
      - type: bind
        source: /mnt/UNRAID_MEDIA/FILMS
        target: /FILMS
        read_only: true
      - type: bind
        source: /mnt/UNRAID_MEDIA/MUSIC_VIDEOS
        target: /MUSIC_VIDEOS
        read_only: true
      - type: bind
        source: /mnt/UNRAID_MEDIA/STANDUP
        target: /STANDUP
        read_only: true
      - type: bind
        source: /mnt/UNRAID_MEDIA/TV_SHOWS
        target: /TV_SHOWS
        read_only: true
      - type: bind
        source: /mnt/UNRAID_MEDIA/XMAS
        target: /XMAS
        read_only: true
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0

**Reply by ghost** [reply]
Sorry for the bad formatting...

**Comment by trythatagain** [comment]
Is this your compose.yml file? I use the 'lscr.io/linuxserver/jellyfin' image, can't remember the reason why, but it's very stable.
I don't have anything apart from volumes when referring to my media, I just find it easier, could you perhaps change the  'bind' statements to volumes?

I  run mine on a AMD 5600, but I'll list the differences I have in my compose.yml file.

```
JELLYFIN_PublishedServerUrl=192.168.x.x`  #optional my server IP
    environment:
      - ROC_ENABLE_PRE_VEGA=1
    group_add:
      - "106" # Change this to match your "render" host group id and remove this comment
      - "44" # Change this to match your "video" 
```
Also as you are using  network_mode: host you shouldn't need ports either.

I've just looked at jellyfin/jellyfin and linuxserver and neither have teh group_add: or ROC_ENABLE_PRE_VEGA=1, so not sure these are needed sorry.
Not sure why the Jellyfin/jellyfin uses the Bind thing, but I think volumes would work just as well.

I suppose you could also spin up a linuxserver Jellyfin and see if this makes any difference.

Not sure if I can suggest anything else, I think I would try linnuxserver image and use volumes for all paths and see how that goes.

**Reply by ghost** [reply]
The compose file is based on the official Jellyfin docker compose as described **[here](https://jellyfin.org/docs/general/installation/container#using-docker-compose)**.

Could you give me an example of what you mean by "change the 'bind' statements to volumes"? Do you mean like this:

```
services:
  jellyfin:
    container_name: arrs1_jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    network_mode: 'host'
    group_add:
      - "105"
    volumes:
      - /home/alex/docker_backup/jellyfin/config:/config
      - /home/alex/docker_backup/jellyfin/cache:/cache
      - /mnt/2TB_DISK/ARRs/watch_or_save:/watch_or_save:ro
      - /mnt/2TB_DISK/HOME_VIDEOS:/HOME_VIDEOS:ro
      - /mnt/UNRAID_MEDIA/ANIMATED:/ANIMATED:ro
      - /mnt/UNRAID_MEDIA/DOCUMENTARIES:/DOCUMENTARIES:ro
      - /mnt/UNRAID_MEDIA/FILMS:/FILMS:ro
      - /mnt/UNRAID_MEDIA/MUSIC_VIDEOS:/MUSIC_VIDEOS:ro
      - /mnt/UNRAID_MEDIA/STANDUP:/STANDUP:ro
      - /mnt/UNRAID_MEDIA/TV_SHOWS:/TV_SHOWS:ro
      - /mnt/UNRAID_MEDIA/XMAS:/XMAS:ro
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
```


I think the lines:

devices:
- /dev/dri/renderD128:/dev/dri/renderD128
- /dev/dri/card0:/dev/dri/card0

shouldn't make any difference because once the container is up, everything is working perfectly fine, all media are playing etc.

Would you like to have a look at:

https://pastebin.com/AAmQSVWB

This is produced with the command
`sudo journalctl -u docker.service --no-tail > docker_daemon.txt`

**Comment by louislam** [comment, marked as answer]
My Jellyfin is working fine.

Normally, with `restart: unless-stopped`, it should restart the container automatically after crash. However, in your case, it didn't.

I think you should create another new Jellyfin stack with minimal configs and mount a local media folder, so that you can determine whether it is the container issue, or config issues, or mount issues (not sure if jellyfin supports NFS/SMB).

Here is my `compose.yaml` for your reference: 

```yaml
services:
  jellyfin:
    ports:
      - 8096:8096
    image: jellyfin/jellyfin
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/user/Videos:/mnt/user/Videos    # Array (XFS)
    restart: unless-stopped
```
