### DISCUSSION TITLE
Dockage breaks outbound SMTP

### DISCUSSION THREAD

**Discussion by dlehman83** [louislam/dockge#573] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

I have been trying to get SMTP working for one of my containers and it kept failing / timing out.  I started troubleshooting at the host level and found dockage to be the issue.  There is no mapping in the compose file to port 25 so this makes no sense.

If the dockage container is stopped, I can telnet to port 25 
when I start the dockage container, telnet to port 25 gets connection refused.  

Below is the output of this test. 

I'm not sure if I have something configured wrong or if I need to open a bug report.  

### 📝 Error Message(s) or Log

root@Docker:/opt/dockge# telnet smtpip 25
Trying smtpip...
Connected to 1 smtpip.
Escape character is '^]'.
220 smtphostname ESMTP Postfix (Ubuntu)
quit
221 2.0.0 Bye
Connection closed by foreign host.
root@Docker:/opt/dockge# cat compose.yaml
``` yaml
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data

      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks
```
root@Docker:/opt/dockge# docker compose up -d
[+] Running 2/2
 ✔ Network dockge_default     Created                                                                                                                    0.1s
 ✔ Container dockge-dockge-1  Started                                                                                                                    0.6s
root@Docker:/opt/dockge# telnet smtpip 25
Trying smtpip...
telnet: Unable to connect to remote host: Connection refused
root@Docker:/opt/dockge#

### 🐻 Dockge Version

1.4.2

### 💻 Operating System and Arch

Ubuntu 24.04 x86_64

### 🌐 Browser

Chrome 126

### 🐋 Docker Version

27.1.0, build 6312585
