### DISCUSSION TITLE
mnt/sdb permission errors on all docker images

### DISCUSSION THREAD

**Discussion by LordSith77** [louislam/dockge#640] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

Every docker image that I try to have the volumes pointing to my /mnt/sdb external gives permission errors. I have scoured Google and found nothing that helps. This is happening for NZBGet, Radarr and Readarr so far.
Example of config files:
```
version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./config:/app/config
      - /mnt/sdb/jellyfin/movies:/movies
      - /mnt/sdb/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
```
Nothing seems to work try to get access to my externally connected drives. I have all the drives set to my user:group, 

### 🐻 Dockge Version

1.4.2

### 💻 Operating System and Arch

Ubuntu Linux 20.04.6

### 🌐 Browser

Google Chrome

### 🐋 Docker Version

24.0.7
