### DISCUSSION TITLE
"Update" notification on Dockge, I'm on 1.4.1 looking to update to 1.4.2

### DISCUSSION THREAD

**Discussion by breeegz** [louislam/dockge#644] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

When I do `docker compose up -d --force-recreate` in the /opt/dockge folder, I would expect to be able to go from 1.4.1 to 1.4.2.  When I looked at the GitHub, I didn't see a version 1.4.1, I saw 1.4.0 and 1.4.2...   am I in some sort of purgatory?

```yaml
version: "3.8"
services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge1
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
```

I'm tagged to the latest, do I need to tag to 1.4.2 to get updated?  (my other instances updated to 1.4.2, I only have this one that is stuck)

### 🐻 Dockge Version

1.4.1

### 💻 Operating System and Arch

Debian in a Proxmox VM

### 🌐 Browser

Brave and Chrome

### 🐋 Docker Version

Docker Compose version v2.29.7
