### DISCUSSION TITLE
Install on Synology NAS

### DISCUSSION THREAD

**Discussion by bebeidon** [louislam/dockge#663] [Ask for Help] [answered]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

I'm trying to run dockge with the following compose.yaml on a Synology NAS:

```
services:
  dockge:
    container_name: dockge
    image: louislam/dockge:1
    network_mode: host
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 9001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/dockge/data:/app/data
      - /volume1/docker/dockge/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks
```
The Synology NAS uses the 5001 port for it's Web User Interface so I change it here to 9001 but I still get errors about 5001 already being in use. I tried 9001:9001 too but still the 5001 error message. Can I not run it in host mode?

### 📝 Error Message(s) or Log

2024/11/13 05:20:32,stderr,Trace: Error: listen EADDRINUSE: address already in use :::5001

2024/11/13 05:20:32,stdout,"[36m2024-11-13T05:20:32+01:00[0m [[32mSERVER[0m] [36mINFO:[0m No user, need setup

### 🐻 Dockge Version

1.4.2

### 💻 Operating System and Arch

Linux NAS 4.4.302+

### 🌐 Browser

Firefox

### 🐋 Docker Version

latest
