### DISCUSSION TITLE
Nginx Proxy Manager

### DISCUSSION THREAD

**Discussion by Amras2322** [louislam/dockge#664] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

I'm trying to set up Nginx Proxy Manager (NPM) in Dockge so that I can access my services (Immich, Vaultwarden, etc) remotely and securely. Here's my compose file for NPM:

```yaml
 nginx-reverse-proxy:
    restart: always
    image: docker.io/jc21/nginx-proxy-manager:latest
    container_name: nginx-reverse-proxy
    volumes:
      - /docker/appdata/npm/data:/data
      - /docker/appdata/npm/letsencrypt:/etc/letsencrypt
    ports:
      - 443:443 # Public HTTPS Port
      - 80:80
      - 81:81 # Admin Web Port
```

My issue is, this stack cannot see containers in other stacks. I can solve this by setting its network mode to host, but when I do I can no longer access the admin web port (gives a warning that network mode: host overrides the port)
      OR
      I can add each other stack as an external network, like so:

```yaml
    networks:
      - dockge_default
      - immich_immich-network
      - n8n_default
      - nut_default
      - vaultwarden_default
```

I thought this solution was working great, but then as I added my hosts I found I'm unable to access Vaultwarden this way, even though I'm setting things up both in NPM and my Cloudflare DNS settings the same way. I understand this may be a Vaultwarden issue, so I'll post this there as well, I just wanted to check if there's a better/recommended way to set up NPM to play more nicely with the other stacks in Dockge.

### 🐻 Dockge Version

1.4.2

### 💻 Operating System and Arch

 Ubuntu noble 24.04 x86_64

### 🌐 Browser

Firefox

### 🐋 Docker Version

Docker version 27.3.1, build ce12230
