### DISCUSSION TITLE
How to add custom path for my compose files?

### DISCUSSION THREAD

**Discussion by Gibbz** [louislam/dockge#688] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

Im setting this up in docker. I want to be able to specify the path to my yml files so I can access the in the web interface.
I want to add them to the volumes, something like:
```  - /path/to/docker-compose-files:/app/data/where```

my config:
```
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dockge:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks
```

### 📝 Error Message(s) or Log

n/a

### 🐻 Dockge Version

latest

### 💻 Operating System and Arch

archlinux

### 🌐 Browser

firefox

### 🐋 Docker Version

latest
