### DISCUSSION TITLE
Admin user and disable auth environment vars at startup

### DISCUSSION THREAD

**Discussion by ToshY** [louislam/dockge#7] [Feature Request]
After setup it currently is required to create an admin user. As I'm already using third-party authentication by default, I was wondering if it's possible to create environment variables to "Disable auth" (like the "Settings > Security > Advanced" option) and/or create an admin user on startup.

**Example**

```yaml
version: '3.9'

services:
  dockge:
    image: louislam/dockge:1
    environment:
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "1234"
      # Or disable dockge auth
      DISABLE_AUTH: true
```

---

Cool new project 👍
