### DISCUSSION TITLE
Does this look correct?

### DISCUSSION THREAD

**Discussion by bonelifer** [louislam/dockge#773] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

Does this look correct?

My base directory is: `/media/william/NewData/homelab/` under it are folders like(with one folder and two files):
```
/projectnamefolder/
./data/
Makefile
docker-compose.yml
```

docker-compose.yml
```
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
        
      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /media/william/NewData/homelab/:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/media/william/NewData/homelab/
```

### 🐻 Dockge Version

current

### 💻 Operating System and Arch

Xubuntu 22.04

### 🌐 Browser

Firfox
