### DISCUSSION TITLE
How to change the default compose file?

### DISCUSSION THREAD

**Discussion by wsw70** [louislam/dockge#776] [Ask for Help] [answered]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

The current default `compose.yml` file when creating a new container is

```yaml
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8080:80
networks: {}
```

Is there a way to modify it?

### 🐻 Dockge Version

1.5.0

### 💻 Operating System and Arch

docker container on Debian 12
