### DISCUSSION TITLE
Allow user provided stack templates

### DISCUSSION THREAD

**Discussion by RichyHBM** [louislam/dockge#78] [Feature Request]
This one might be a harder one to add, but in my case I often have lots of boilerplate in my compose file, if there were a way to use a JS/TS templating language to provide a custom template to use when creating new stacks, that provides variables for some of the fields, that would be great. As an example that could look like something like:

template.dockge
```
---
services:
  %{service_name}:
    image: %{service_image}
    container_name: %{service_name}
    networks:
      - my_network
    volumes:
      - /config/%{service_name}:/app/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.services.%{service_name}.loadbalancer.server.port=5001
      - traefik.http.services.%{service_name}.loadbalancer.server.scheme=http
      - traefik.http.routers.%{service_name}.middlewares=authelia@file
      # Homepage
      - homepage.name=%{service_name}
      - homepage.href=https://%{service_name}.subdomain.domain.com/

```
