### DISCUSSION TITLE
Setting persisting for an app across deletions. Both in the UI and with =docker volume rm=

### DISCUSSION THREAD

**Discussion by trharmon0** [louislam/dockge#802] [Ask for Help]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 📝 Describe your problem

I have been playing with the motioneye app (https://github.com/motioneye-project/motioneye/issues/3151) managed with dockge. During that process I have done things like:

- configure the motioneye admin password
- configure motioneye for access to a USB web cam

When I delete the app instance from dockge, even if I drop to the CLI on the node hosting dockge and manually delete any lingering docker volumes, I'm getting the same settings when I create a new instance of the motioneye app and start via the dockge interface. I've always cleared the cookies in the brower I  use to access the motioneye app.

There's some sort of config caching that is happening between creation and start of the motioneye instances but I'll be darned if I can figure out where. Not cookies; not docker volumes. Something in a database within dockge itself?

Here's the manifest used to spin motion eye. I have not been setting anything in .env.

```yaml
services:
  motioneye:
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 8765:8765
    hostname: motioneye
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/motioneye/config:/etc/motioneye
      - /data/motioneye/videos:/var/lib/motioneye
    image: ccrisan/motioneye:master-amd64
networks: {}
```

### 🐻 Dockge Version

latest

### 💻 Operating System and Arch

PRETTY_NAME="Debian GNU/Linux 13 (trixie)"

### 🌐 Browser

librewolf 138.0.3-1

### 🐋 Docker Version

28.1.1
