### DISCUSSION TITLE
New stacks being created with root owner

### DISCUSSION THREAD

**Discussion by RichyHBM** [louislam/dockge#89] [Feature Request]
Hi, I have noticed that when creating a new stack, the owner of the stack/compose file is set to the container user, could we supply a user/group to assign it to maybe in the environment variables? It seems `PUID=1000 PGID=1000` seem to have become the standard env variables to use for this

**Comment by jtabox** [comment]
Yes please. This is a great piece of software and I'm so looking forward to fully swap Portainer with it, but I can't until it allows creating stacks as any other user than root (+1 for `PUID=1000`, `PGID=1000`). Usually I have stuff inside my containers' mapped folders that I want shared on my LAN, and it's kinda bothersome to manually chown -R everything as soon as it's created and hope nothing breaks.

**Comment by trythatagain** [comment]
For me a quick work around would be if the Group had write permission, that allows me to edit the stacks from within a browser. I only use Linux if that makes a difference.

**Comment by sabamimi** [comment]
Totally agree with this  RichyHBM comment.
This would be very usefull improvement since YAML file can/could be edited outside Dockge.
So definitively +1 for PUID=1000, PGID=1000

**Comment by stayupthetree** [comment]
April 2024, still not a feature. Was excited to try this out, came across the stack being root immediately and it causes problems. Please fix! Someone has already done the work months ago and submitted a PR. https://github.com/louislam/dockge/pull/83/commits/9f6a3eea322f66cdc3fe12d4016106a7c92ba5bb

**Comment by fxlrnrpt** [comment]
Just add a `user` directive and a `group_add` to your compose file, and it is going to have the right permissions:
```yaml
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    user: 1000:1000
    group_add:
      - '996'
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
        
      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks
```

As you can see, under `services.dockge` I added `user: 1000:1000`, where 1000:1000 is PUID and GUID of my user. Also, notice the new `group_add` entry. It points to the numerical value of the `docker` group on my machine. See https://stackoverflow.com/a/71826051 for more info
