### DISCUSSION TITLE
[GETSTACKLIST] WARN: Failed to get stack .gitignore, error: Maximum call stack size exceeded

### DISCUSSION THREAD

**Discussion by ToshY** [louislam/dockge#9] [General]
**Problem**

Dockge fails on startup when the mounted host directory contains files (e.g. `.gitignore`).

```text
./collection/
├── kuma
├── dockge
├── .gitignore
├── LICENSE
└── README.md
```

`./collection/dockge/docker-compose.yml`

```yaml
version: '3.9'

x-restart: &restart-always
  restart: always

services:
  dockge:
    image: louislam/dockge:${DOCKGE_IMAGE_VERSION}
    <<: [*restart-always]
    security_opt:
      - no-new-privileges:true
    environment:
      DOCKGE_STACKS_DIR: ${DOCKGE_STACKS_DIR_CONTAINER:-/opt/stacks}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockge:/app/data
      - ${DOCKGE_STACKS_DIR_HOST:-/opt/stacks}:${DOCKGE_STACKS_DIR_CONTAINER:-/opt/stacks}
    networks:
      - dockge
      - proxy

volumes:
  dockge:
    driver: local

networks:
  dockge:
    driver: bridge
  proxy:
    external: true
```

`.env`
```dotenv
DOCKGE_IMAGE_VERSION="1"
DOCKGE_STACKS_DIR_HOST="../" # resolves to "./collection" on host
DOCKGE_STACKS_DIR_CONTAINER=
```

Run `docker compose up`

```shell
dockge-dockge-1  | 2023-11-12T14:31:00.357375696Z prebuild-file-path: /app/node_modules/.pnpm/@homebridge+node-pty-prebuilt-multiarch@0.11.10/node_modules/@homebridge/node-pty-prebuilt-multiarch/prebuilds/linux-x64/node.abi115.node
dockge-dockge-1  | 2023-11-12T14:31:00.458110826Z 2023-11-12T14:31:00Z [SERVER] INFO: Welcome to dockge!
dockge-dockge-1  | 2023-11-12T14:31:00.458681564Z 2023-11-12T14:31:00Z [SERVER] INFO: NODE_ENV: production
dockge-dockge-1  | 2023-11-12T14:31:00.460918022Z 2023-11-12T14:31:00Z [SERVER] INFO: Data Dir: ./data/
dockge-dockge-1  | 2023-11-12T14:31:00.461837194Z 2023-11-12T14:31:00Z [SERVER] INFO: Server Type: HTTP
dockge-dockge-1  | 2023-11-12T14:31:00.466830291Z 2023-11-12T14:31:00Z [DB] INFO: Database Type: sqlite
dockge-dockge-1  | 2023-11-12T14:31:00.505587416Z 2023-11-12T14:31:00Z [SERVER] INFO: Connected to the database
dockge-dockge-1  | 2023-11-12T14:31:00.520457139Z 2023-11-12T14:31:00Z [SERVER] INFO: Listening on 5001
dockge-dockge-1  | 2023-11-12T14:31:09.076066899Z 2023-11-12T14:31:09Z [SERVER] INFO: Socket connected!
dockge-dockge-1  | 2023-11-12T14:31:09.081891315Z 2023-11-12T14:31:09Z [AUTH] INFO: Login by token. IP=172.19.0.3
dockge-dockge-1  | 2023-11-12T14:31:09.084335072Z 2023-11-12T14:31:09Z [AUTH] INFO: Username from JWT: ToshY
dockge-dockge-1  | 2023-11-12T14:31:09.156599613Z 2023-11-12T14:31:09Z [GETSTACKLIST] WARN: Failed to get stack .gitignore, error: Maximum call stack size exceeded
```

**Solution**

Ignore files in mounted directory.
