### ISSUE TITLE
"inactive" dockge in dockge

### ISSUE THREAD

**Issue by WindWT** [louislam/dockge#100]
Is it intended or bug?

everything is lowercase, so it can't be  #19 

![image](https://github.com/louislam/dockge/assets/1337002/8f24e374-7b29-47ea-999a-0d36487396d9)

and terminal works :)

![image](https://github.com/louislam/dockge/assets/1337002/f0f1b9f9-69f9-4bb1-96f0-69b626c2218d)

update: folder structure like below, only dockge itself shows `inactive`
```
docker
├── some-service
│   ├── config
│   └── docker-compose.yml
├── some-other-service
│   ├── cache
│   ├── data
│   └── docker-compose.yml
├── dockge
│   ├── data
│   └── docker-compose.yml
```

**Comment by Stunt0265** [comment]
Check to see if you placed your dockge compose.yaml file in the "stacks" directory.

**Comment by Trigant** [comment]
I second op's problem.

compose.yaml:
```
version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    ports:
      - 5022:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /home/huddeij/docker:/home/huddeij/docker
    environment:
      - DOCKGE_STACKS_DIR=/home/huddeij/docker
```

compose.yaml lies in this folder:
`/home/huddeij/docker/dockge`

![image](https://github.com/louislam/dockge/assets/6482096/d15f7a59-613f-4c38-b14e-0474ef3e3b99)

but in `/home/huddeij/docker/` are all folders for my docker containers and therefore the compose files
proof that it works:
![image](https://github.com/louislam/dockge/assets/6482096/c9702b88-496f-448d-b903-bf842ac388eb)

but the same folder structure
`/home/huddeij/docker/gitea`
`/home/huddeij/docker/homepage`
etc
