### ISSUE TITLE
Commented out lines in compose file disappear when starting/deploying container.

### ISSUE THREAD

**Issue by JohnDoe-dev-spec** [louislam/dockge#176]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

I have created a new stack with Dockge and commented out some lines in the YAML with # 

I then start/deploy the stack and it creates successfully and refreshed the page. The compose.yaml no longer shows me the commented out line, it disappears.

I then login to the host and nano compose.yaml and i can see the commented out line there but not in Dockge.

### 👟 Reproduction steps

Create stack and comment out line
Deploy/start stack
Refresh Page

Line disappears

### 👀 Expected behavior

The commented out line still to appear in my compose.yaml so i can reintroduce it if i want to.

### 😓 Actual Behavior

Commented out line disappears from Dockge GUI

### Dockge Version

1.1.1.1

### 💻 Operating System and Arch

DietPI Debian

### 🌐 Browser

Firefox/Chrome

### 🐋 Docker Version

Docker 24.0.7

### 🟩 NodeJS Version

N/A

**Comment by cirrusflyer** [comment]
Noticed this too.

**Comment by louislam** [comment]
Need example, I cannot reproduce. Still there after refresh.

![image](https://github.com/louislam/dockge/assets/1336778/f9fd24d7-a7b9-4d74-83ff-ab203645ab4a)

**Comment by JohnDoe-dev-spec** [comment]
I can't seem to reproduce it either anymore. 

It did disappear!

Close this off for now and if it happens again i will re-open with example.

Thanks!

**Comment by marvint24** [comment]
It's seams like that this is still an issue.
Steps to reproduce:

- Create a new compose
- Paste:
```
version: "3.8"
services:
  nginxpm:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - 80:80
      # test comment
      - 443:443
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    restart: unless-stopped
volumes:
  nginx_data: 
  nginx_letsencrypt: 
  ```
- Save
- Edit
