### ISSUE TITLE
stack marked as "exited" when conatiners are running 

### ISSUE THREAD

**Issue by zx900930** [louislam/dockge#177]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

I'm trying to deploy this project using dockge
https://github.com/makeplane/plane
but it was marked as exited even if those containers are running.
![image](https://github.com/louislam/dockge/assets/734749/3d21898c-6a39-4e71-a721-349106c7bac0)

### 👟 Reproduction steps

1. cd /opt/stacks
2. git clone https://github.com/makeplane/plane.git
3. hit the deploy button on dockge

### 👀 Expected behavior

Stack will be marked as ''active'' when containers starts running.

### 😓 Actual Behavior

Stack marked as ''exited'' when containers starts running.

### Dockge Version

1.1.1

### 💻 Operating System and Arch

Debian GNU/Linux 12 (bookworm) x86_64

### 🌐 Browser

Google Chrome 119.0.6045.160

### 🐋 Docker Version

Docker CE 24.0.7

**Comment by louislam** [comment]
I tried this stack, I saw the `minio` container is not started, I think it is the reason, because the stack is active only if all containers are up.

**Comment by zx900930** [comment]
> I tried this stack, I saw the `minio` container is not started, I think it is the reason, because the stack is active only if all containers are up.

That `createbuckets` minio container is an init task, like the `jobs` in k8s, once the needed bucket is created, it will exit.

Can we add a filter (using labels for example: `- "dockge.stack.status.enable=false"` ) to exclude containers from being checked by dockge?

**Comment by Yann-J** [comment]
I have a similar issue with a Plex compose file, which contains an init container that installs/updates some plugins, then exits. There is a `depends_on: {plex_plugins:{condition: service_completed_successfully}}` condition on the main plex container

**Comment by Yann-J** [comment]
Looking a bit into the code, I fear this might be tricky to implement, as right now [the status is computed](https://github.com/louislam/dockge/blob/master/backend/stack.ts#L255) based on parsing the response from `docker compose ls` which will return something like `exited(1), running(2)`, without further details...

**Comment by thefrana** [comment]
I also encountered this issue and all responses from `docker compose ls` are in status `running`. It still shows exited in the UI.

**Comment by queeup** [comment]
Same here.  I am using bash container to do some jobs before services start like init task.

```yml
version: "3"
services:
  bash:
    image: bash:latest
    container_name: bash
    network_mode: none
    user: 1000:100
    volumes:
      - /container-data:/container-data
    restart: no
    command: -c 'mkdir -p
      /container-data/{sonarr/config,radarr,prowlarr/config,bazarr/config,transmission/{config,custom-cont-init.d}}'
  transmission:
    image: ghcr.io/linuxserver/transmission:latest
    container_name: transmission
    hostname: transmission
    networks:
      - servarr
    depends_on:
      - bash
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Istanbul
    volumes:
      - /container-data/transmission/config:/config
      - /container-data/transmission/custom-cont-init.d:/custom-cont-init.d:ro
      - /data/downloads:/data/downloads:shared
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
```
