### ISSUE TITLE
Compose files not seen

### ISSUE THREAD

**Issue by Aviortheking** [louislam/dockge#250]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

I have no compose files seen + it seems that it stop detecting state of compose
![image](https://github.com/louislam/dockge/assets/15822031/2619b726-9a02-4b54-925f-5221d8d22d31)
*the token shown in my compose is out of date*

### 👟 Reproduction steps

- create a `docker-compose.yml` out of the `/opt/stacks` folder file with 
```
version: "3.3"
services:
  uptime-kuma:
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    image: louislam/uptime-kuma:1
    networks:
      - coolify-infra
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.rule=Host(`uptime.dzeio.com`)
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
      - traefik.http.routers.uptime-kuma.tls.certresolver=letsencrypt
```
- run `docker-compose up -d`
- run `docker-compose stop`
- delete the `docker-compose.yml` file

I think you have to create a compose file an up it once, stop it and delete the compose file
(out of dockge stacks folder)

as the container `491e4c1cac31a1be74020030eb10e5d259a2a820a501ab10e1b8223b36e642f7` was made in another folder but the compose file is not present anymore (also the container is down)

### 👀 Expected behavior

we should be able to see the list of stacks	and manipulate active containers

### 😓 Actual Behavior

we don't see the list of stacks and can't manipulate active composes

### Dockge Version

1.3.2

### 💻 Operating System and Arch

Linux SRV1 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

### 🌐 Browser

Firefox 119.0.1

### 🐋 Docker Version

Docker version 20.10.24+dfsg1, build 297e128

### 📝 Relevant log output

```shell
dockge_1  |     at process.unexpectedErrorHandler (/app/backend/dockge-server.ts:76:21)
dockge_1  |     at process.emit (node:events:514:28)
dockge_1  |     at process.emit (/pnpm/global/5/.pnpm/tsx@4.5.0/node_modules/tsx/dist/suppress-warnings.cjs:1:472)
dockge_1  |     at emit (node:internal/process/promises:149:20)
dockge_1  |     at processPromiseRejections (node:internal/process/promises:283:27)
dockge_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
dockge_1  | If you keep encountering errors, please report to https://github.com/louislam/dockge
dockge_1  | Trace: Error: Process exited with code 1
dockge_1  |     at ChildProcess.done (/app/node_modules/.pnpm/promisify-child-process@4.1.2/node_modules/promisify-child-process/index.cjs:70:19)
dockge_1  |     at ChildProcess.emit (node:events:514:28)
dockge_1  |     at ChildProcess.emit (node:domain:489:12)
dockge_1  |     at maybeClose (node:internal/child_process:1091:16)
dockge_1  |     at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
dockge_1  |   code: 1,
dockge_1  |   signal: null,
dockge_1  |   stdout: '',
dockge_1  |   stderr: 'No label "com.docker.compose.project.config_files" set on container "491e4c1cac31a1be74020030eb10e5d259a2a820a501ab10e1b8223b36e642f7" of compose project\n'
dockge_1  | }
```

**Comment by louislam** [comment]
The reproduce steps is not clear and don't quite understand, because you said you deleted the compose file.

Isn't expected? because you deleted the compose file and won't able to show in the list.

**Comment by Aviortheking** [comment]
another explanation :
- create a `docker-compose.yml` out of the `/opt/stacks` folder file with 
```
version: "3.3"
services:
  uptime-kuma:
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    image: louislam/uptime-kuma:1
    networks:
      - coolify-infra
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.rule=Host(`uptime.dzeio.com`)
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001
      - traefik.http.routers.uptime-kuma.tls.certresolver=letsencrypt
```
- run `docker-compose up -d`
- run `docker-compose stop`
- delete the `docker-compose.yml` file

You will have a stopped container with a non existing compose file
