### ISSUE TITLE
NetworkMode in HostConfig is set inconsistently

### ISSUE THREAD

**Issue by alex3305** [louislam/dockge#290]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

Recently I deployed a new stack and I noticed in my unRAID Docker tab that the network was set to a hash instead of a name:

![image](https://github.com/louislam/dockge/assets/5155694/764312cd-32a0-43dc-abf6-60ed5735ef73)

For some stacks this is true for some containers, but not others:

![image](https://github.com/louislam/dockge/assets/5155694/88a89687-0f10-47a1-b3f8-88cedd304076)

After inspecting the container from CLI I get this output:

```
$ docker inspect -f "{{ .HostConfig.NetworkMode }}" homeassistant
80c43f9f7b35a2984292ff7cf0d20db286d39ff6bb6132c1ec18a044ff5ae32d
$ docker inspect -f "{{ .HostConfig.NetworkMode }}" homeassistant_mariadb
homeassistant

$ docker inspect -f "{{ .HostConfig.NetworkMode }}" immich_server
immich
$ docker inspect -f "{{ .HostConfig.NetworkMode }}" immich_redis
immich

$ docker inspect -f "{{ .HostConfig.NetworkMode }}" owntracks_recorder
80c43f9f7b35a2984292ff7cf0d20db286d39ff6bb6132c1ec18a044ff5ae32d
```

These stacks are all very different, but even so this seems very inconsistent. 

### OwnTracks ⛔

```yaml
---
services:
  recorder:
    container_name: owntracks_recorder
    image: owntracks/recorder
    networks:
      br0:
        ipv4_address: 192.168.1.200

networks:
  br0:
    name: br0
    external: true
```

### Immich ✅

```yaml
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    depends_on:
      - redis
    networks:
      immich: 
      br0:
        ipv4_address: '192.168.1.199'
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    networks:
      immich: 

networks:
  immich:
    name: immich
  br0:
    name: br0
    external: true
```

### Home Assistant ⛔

```yaml
---
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    networks:
      homeassistant: 
      br0:
        ipv4_address: 192.168.1.201
    depends_on:
      - mariadb
  mariadb:
    container_name: homeassistant_mariadb
    image: mariadb:10.7
    networks:
      homeassistant: 

networks:
  homeassistant:
    name: homeassistant
  br0:
    name: br0
    external: true
```

Besides these stacks I also have deployed Paperless NGX and Spotweb the same way and both work correctly and show the friendly name in NetworkMode, This also didn't happen when I used Portainer previously.

### 👟 Reproduction steps

Deploy any stack and check whether or not the NetworkMode was set to a friendly name:

```bash
docker inspect -f "{{ .HostConfig.NetworkMode }}" CONTAINER_NAME
```

### 👀 Expected behavior

Having a friendly name as a network mode.

### 😓 Actual Behavior

A hash appears instead of a friendly name.

### Dockge Version

1.3.3

### 💻 Operating System and Arch

unRAID 6.12.5

### 🌐 Browser

Brave

### 🐋 Docker Version

Docker 20.10.24
