### ISSUE TITLE
Stacks not showing anymore after updating to 1.3.4

### ISSUE THREAD

**Issue by Jayllyz** [louislam/dockge#306]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

I ran `docker-compose pull && docker-compose up -d` to update Dockge, but now my stacks aren't showing in Dockge.

![image](https://github.com/louislam/dockge/assets/16305216/7459e106-9fed-4d11-8800-5a7bc5e22557)

### 👟 Reproduction steps

`docker compose pull && docker compose up -d`

### 👀 Expected behavior

Update dockge

### 😓 Actual Behavior

Stacks showing

### Dockge Version

1.3.4

### 💻 Operating System and Arch

Ubuntu 23.10

### 🌐 Browser

Google Chrome 119.0.6045.200

### 🐋 Docker Version

24.0.7

**Comment by ivrancic** [comment]
I have the same issue on Raspberry Pi 4B. The subdirectory /stack has not been created on the host. I used the following command to pull image and create container: `docker compose up -d`.
The compose.yaml file is:
```
version: "3.8"
services:
  dockge:
    image: louislam/dockge:latest
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/dockge/data:/app/data
      - /home/docker/stacks:/home/docker/stacks
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/home/docker/stacks
```
