### ISSUE TITLE
.env using symlinks are not properly detected

### ISSUE THREAD

**Issue by thatg33khub** [louislam/dockge#372]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

The gui does not detect .env files when they are symlinks. It generate errors when starting/updating/stopping containers.
Manually running the 'docker compose up or down' commands from a terminal works fine.

### 👟 Reproduction steps

**Example of setup**

**Folder structure**
DOCKGE_STACKS_DIR=/opt/stacks
![image](https://github.com/louislam/dockge/assets/93085781/4cb4f3c5-1e3e-4d15-9180-137b75787316)

**Compose example**
```
version: "3.0"
services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    volumes:
      - ${appdata}/memos/:/var/opt/memos
    ports:
      - ${memos_port}:5230
    restart: unless-stopped
    networks:
      - dockernet
networks:
  dockernet:
    external: true
```

**extract of .env file**
appdata=/path/to/appdata
memos_port=5230

### 👀 Expected behavior

The .env file is detected by the GUI when editing the stack. It is considered when running the start, stop or update commands, like a manual command would:
![image](https://github.com/louislam/dockge/assets/93085781/c6eb43bd-5ff5-49d1-9540-49127f22bc25)

### 😓 Actual Behavior

Editing the stack shows an empty .env
![image](https://github.com/louislam/dockge/assets/93085781/8104e00f-0b40-4d8f-80ee-37375ba62985)

Trying to start the container -> log shows that variables are missing:
WARN[0000] The "appdata" variable is not set. Defaulting to a blank string. 
WARN[0000] The "memos_port" variable is not set. Defaulting to a blank string. 
[+] Restarting 1/1
 ✔ Container memos  Started     

### Dockge Version

1.4.0

### 💻 Operating System and Arch

Debian x86_64

### 🌐 Browser

Brave 1.61.116 / Chrome 120.0.0699.217

### 🐋 Docker Version

Docker version 24.0.7

### 📝 Relevant log output

```shell
WARN[0000] The "appdata" variable is not set. Defaulting to a blank string. 
WARN[0000] The "memos_port" variable is not set. Defaulting to a blank string. 
service "memos" is not running
```
