### ISSUE TITLE
paperless-ngx: running stack is shown as inactive

### ISSUE THREAD

**Issue by JarlMorgennebel** [louislam/dockge#474]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

paperless-ngx is up and running fine. DockGE reports the stack as inactive, even when restarted from command line.

```
root@wyse-5070-wan-docker:/opt/stacks/paperless-ngx# cat compose.yml 
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:6.0
    restart: unless-stopped
    volumes:
      - ./redis_data:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8000:8000
        #    healthcheck:
        #      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
        #      interval: 30s
        #      timeout: 10s
        #      retries: 5
    volumes:
      - ./paperless_data:/usr/src/paperless/data
      - ./paperless_media:/usr/src/paperless/media
      - ./paperless_export:/usr/src/paperless/export
      - ./paperless_consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.4
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped

volumes:
  paperless_data:
  paperless_media:
  postgres_dataa:
  redis_data:
```

### 👟 Reproduction steps

docker-compose up -d
Wait 60 secs

### 👀 Expected behavior

Stack status shown as active as all other stacks

### 😓 Actual Behavior

Stack status shown as inactive as only exception

### Dockge Version

1.4.2

### 💻 Operating System and Arch

Devuan Daedalus (Debian without systemd)

### 🌐 Browser

Vivaldi

### 🐋 Docker Version

docker 20.10.24+dfsg1

### 📝 Relevant log output

```shell
root@wyse-5070-wan-docker:/opt/stacks/paperless-ngx# docker ps | grep paper
03d2cd7586e9   ghcr.io/paperless-ngx/paperless-ngx:latest   "/sbin/docker-entryp…"   15 minutes ago   Up 15 minutes (healthy)   0.0.0.0:8000->8000/tcp                        paperless_webserver_1
2a1dde83983a   ghcr.io/paperless-ngx/tika:latest            "/bin/sh -c 'exec ja…"   15 minutes ago   Up 15 minutes             9998/tcp                                      paperless_tika_1
45fe588780d1   postgres:13                                  "docker-entrypoint.s…"   15 minutes ago   Up 15 minutes             5432/tcp                                      paperless_db_1
424cd693d10c   redis:6.0                                    "docker-entrypoint.s…"   15 minutes ago   Up 15 minutes             6379/tcp                                      paperless_broker_1
c0f45ce8ced7   gotenberg/gotenberg:7.4                      "/usr/bin/tini -- go…"   15 minutes ago   Up 15 minutes             3000/tcp                                      paperless_gotenberg_1
```
