### ISSUE TITLE
Are .env files supported?

### ISSUE THREAD

**Issue by Dima-Kal** [louislam/dockge#48]
Im using .env file for all my stacks, and all of them report missing vars:

WARN[0000] The "DOCKER_STORAGE_PATH" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_NETWORK" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SERVER_DOMAIN" variable is not set. Defaulting to a blank string. 
WARN[0000] The "SERVER_DOMAIN" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DOCKER_NETWORK" variable is not set. Defaulting to a blank string.

**Comment by ToshY** [comment]
I'm also using `.env` for my existing stacks in dockge without any console warnings when starting the stack. How does your `compose.yaml` for your stack look like then?

**Comment by Dima-Kal** [comment]
For example:

```
  authelia:
    image: authelia/authelia:v4.38.0-beta2
    container_name: authelia
    user: "1000"
    volumes:
      #- ./authelia:/config
      - "./configs/authelia/authelia-config.yml:/config/configuration.yml:ro"
      - "./configs/authelia/authelia-users-database.yml:/config/users_database.yml:ro"
      - "./configs/authelia/private.pem:/config/private.pem:ro"
      - "${DOCKER_STORAGE_PATH}/network/authelia/config:/config"
    networks:
      - ${DOCKER_NETWORK}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`authelia.${SERVER_DOMAIN}`, `auth.${SERVER_DOMAIN}`)"
     ```
