### ISSUE TITLE
Connection to remote aggent with reverse proxy in front does not work

### ISSUE THREAD

**Issue by pandel** [louislam/dockge#501]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

I setup all my Dockge instances to be served by a Nginx reverse proxy and wanted to connect them to my main Dockge instance. but that does not work.

### 👟 Reproduction steps

Setup like this:

**compose.yaml**

```
version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    expose:
      - 5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt/docker:/opt/docker
    environment:
      - DOCKGE_STACKS_DIR=/opt/docker

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "5001:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
```

**nginx.conf**

```
server {
  listen 443 ssl http2;
  # Remove '#' in the next line to enable IPv6
  # listen [::]:443 ssl http2;
  server_name server.name.redacted;
  ssl_certificate     /etc/nginx/certs/server.name.redacted.crt;
  ssl_certificate_key /etc/nginx/certs/server.name.redacted.key;
  # *See "With SSL (Certbot)" below for details on automating ssl certificates

  location / {
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   Host $host;
    proxy_pass         http://dockge:5001/;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
  }
}
```

### 👀 Expected behavior

Agent connection established.

### 😓 Actual Behavior

Sadly, if I try to connect an instance as agent to my main instance I get "Unable to connect to the Dockge instance."

### Dockge Version

1.4.2

### 💻 Operating System and Arch

Debian 11

### 🌐 Browser

Firefox

### 🐋 Docker Version

25.0.3

### 🟩 NodeJS Version

N/A

### 📝 Relevant log output

```shell
No log output writte regarding this error.
```
