### ISSUE TITLE
docker compose 'version' is obsolete

### ISSUE THREAD

**Issue by GerdRuetten** [louislam/dockge#505]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

In the actual docker compose, the 'version' element in the compose.yaml is obsolet and throw a warning.

See:
https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-and-name-top-level-elements

### 👟 Reproduction steps

create a new stack

### 👀 Expected behavior

compose.yaml without 'version' element

```
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8080:80
networks: {}

```

### 😓 Actual Behavior

compose.yaml with 'version' element

```
version: "3.8"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8080:80
networks: {}

```

### Dockge Version

1.4.2

### 💻 Operating System and Arch

linux/amd64

### 🌐 Browser

not browser specifik

### 🐋 Docker Version

Docker 26.0.0
