### ISSUE TITLE
Compose Volume Failure on subpath

### ISSUE THREAD

**Issue by ZeroInputCtrl** [louislam/dockge#520]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

When trying to use the latest volume subpath feature, validation fails and refuses to up the stack. Note this also happens on portainer as well. `docker compose up` in the stack directory works just fine. 
Not sure what is being used for compose validation but it doesn't seem to be up to date.
```
root@docker:/stacks/data# docker compose config --quiet && printf "OK\n" || printf "ERROR\n"
=> OK
```

### 👟 Reproduction steps

Create a external volume (in my case i'm using cifs)
Create a service in a stack that uses said volume with the volume -> subpath
Save and start the stack

volume example
```
   volumes:
      - type: volume
        source: appdata
        target: /backups
        volume:
          nocopy: true
          subpath: nextcloud
```

### 👀 Expected behavior

Stack to be started with no issues

### 😓 Actual Behavior

error raised
validating /stacks/data/compose.yaml: services.next.volumes.5.volume Additional property subpath is not allowed

### Dockge Version

1.4.2

### 💻 Operating System and Arch

Debian x64

### 🌐 Browser

Firefox

### 🐋 Docker Version

26.1.2 - Docker Compose version v2.27.0
