### ISSUE TITLE
line numbers is not correct when a line is too long

### ISSUE THREAD

**Issue by eslym** [louislam/dockge#530]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

line numbers is not correct when a line is too long

### 👟 Reproduction steps

```yaml
version: "3.8"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8080:80
  environment:
    LONG_VALUE: this is a very long long long long long long long long long long long long long long long long long long long long long long long long long value.
networks: {}
```

### 👀 Expected behavior

line number should not be shown when a line is wrap

### 😓 Actual Behavior

![image](https://github.com/louislam/dockge/assets/3667594/4369a258-f435-42f2-96fe-e7a6decf4e7a)

### Dockge Version

1.4.2

### 💻 Operating System and Arch

Bebian bookworm (Rasbian OS) arm64

### 🌐 Browser

Google Chrome 125.0.6422.60

### 🐋 Docker Version

Docker version 26.1.1, build 4cf5afa

### 🟩 NodeJS Version

v18.17.1
