### ISSUE TITLE
Docker Watch Support?

### ISSUE THREAD

**Issue by ForsakenRei** [louislam/dockge#632]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

I'm using docker compose watch https://docs.docker.com/compose/how-tos/file-watch/ to do some development and it seems if I have develop section in my compose file, dockge won't be able to start/restart/stop the container.

### 👟 Reproduction steps

My compose file
```
services:
  web:
    build: .
    container_name: my-application
    ports:
      - 8895:80
    develop:
      watch:
        - action: sync
          path: ./app
          target: /var/www/localhost/htdocs/
```
And try to start/stop the container with dockge

### 👀 Expected behavior

The container can be started with `docker compose up -d` so techincally it should be able to start with dockge?

### 😓 Actual Behavior

Dockge will return error
```
validating /{mypath}/compose.yaml: service.web Additional property develop is not allowed

### Dockge Version

1.4.2

### 💻 Operating System and Arch

Oracle Linux 9.4

### 🌐 Browser

Chrome 129

### 🐋 Docker Version

Docker 27.3.1

### 🟩 NodeJS Version

20.15.0

### 📝 Relevant log output

_No response_
