### ISSUE TITLE
The web editor will the `dockerfile_inline` element when editing

### ISSUE THREAD

**Issue by lildata** [louislam/dockge#673]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

I encounter a strange web editor behavior when I edit a docker compose file with the `dockerfile_inline` element https://docs.docker.com/reference/compose-file/build/#dockerfile_inline

When I click `Edit` the editor will modify the inline dockerfile (`|` is replaced by `>` and a line is inserted between each lines)
I did check (cat `/opt/stacks/xxx/compose.yaml`) it really happens at the opening for edit.

I do not see any error in the Console of the browser Web developer tools

### 👟 Reproduction steps

1. Create a Compose with the `dockerfile_inline` element 
2. Save the file
3. Edit the Compose (bug)

### 👀 Expected behavior

I would expect my inline dockerfile not to be modified by the editor

```yaml
build:
  context: .
  dockerfile_inline: |
    FROM baseimage
    RUN some command  
    ENTRPOINT hello
```

### 😓 Actual Behavior

instead the `|` is replaced by `>` and a line is inserted between each lines of the inline dockerfile

```yaml
build:
  context: .
  dockerfile_inline: >
    FROM baseimage

    RUN some command  

    ENTRYPOINT hello
```

I do not see any error in the Console of the browser Web developer tools

### Dockge Version

1.4.2

### 💻 Operating System and Arch

Alpine / amd64

### 🌐 Browser

Chromium: 129 and Firefox 131

### 🐋 Docker Version

Docker 26.1.5
