### ISSUE TITLE
spawn docker ENOENT with Root project Directory Dockfile(s) 

### ISSUE THREAD

**Issue by matt-falkner** [louislam/dockge#675]
System Info 
- MacOS 15, Apple Silicon 

Project structure. I don't have a stacks folder, all the source files are in the root project directory. 
```bash 
---ProjectSourceCodeFiles---
---ProjectBuildFiles---
Dockerfile.project-dev.yml
Dockerfile.project-prod.yml
Docker-compose.dev.yml
Docker-compose.prod.yml
Docker-compose.dockage.yml
```

Docker compose dockage file 
```yaml
version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /Users/xxx/Documents/Development/ProjectName:/Users/xxx/Documents/Development/ProjectName
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/Users/xxx/Documents/Development/ProjectName

```

Gets this error. 

```
Error: spawn docker ENOENT
   at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
   at __node_internal_errnoException (node:internal/errors:623:12)
   at ChildProcess._handle.onexit (node:internal/child_process:283:19)
   at onErrorNT (node:internal/child_process:476:16)
   at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
   errno: -2,
   code: 'ENOENT',
   syscall: 'spawn docker',
  path: 'docker',
  spawnargs: [ 'compose', 'ps', '--format', 'json' ]
}
```

However, when I add a temporary /stacks/stackname folder(s) it starts working. But I cannot do this in practice because of how my project is structured. I believe the error is related to the project structure but cannot confirm. Have done a lot of trial and error. 

Any ideas?
