### ISSUE TITLE
Imported stacks not showing full compse file.

### ISSUE THREAD

**Issue by Jadan1213** [louislam/dockge#68]
using louislam/dockge:latest

I installed Dockge and moved a couple containers into the stacks folder. I can start, stop, and update the containers, as well as view the real time log, however the compose file doesn't show up properly.

For example: 
This is my compose file for Grocy;
```
---
version: "3.8"
services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./data:/config
    ports:
      - 9283:80
    restart: unless-stopped
    memswap_limit: "512M"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"
```

However in Dockge it's only showing;
```
1. services: {}
2. version: "3.8"
3. networks: {}
4.
```
