### ISSUE TITLE
Compose.yaml edits won't save

### ISSUE THREAD

**Issue by truthsword** [louislam/dockge#693]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

Trying to edit container name. When I click Save I get:

![](https://i.imgur.com/cMNgzwM.png)

### 👟 Reproduction steps

Edit any compose file and click Save.

![](https://i.imgur.com/cMNgzwM.png)

### 👀 Expected behavior

No error

### 😓 Actual Behavior

![](https://i.imgur.com/cMNgzwM.png)

Here is my compose.yaml
```
services:
  dockge:
    image: louislam/dockge:latest
    restart: unless-stopped
    container_name: dockge
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks # this is the container side
    network_mode: bridge
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/app/data
      - /home/me/stacks:/opt/stacks
volumes:
    data:
```

### Dockge Version

1.4.2

### 💻 Operating System and Arch

Debian 12

### 🌐 Browser

LibreWolf 133.0.3-1

### 🐋 Docker Version

27.4.1

### 📝 Relevant log output

```shell
dockge  | 2024-12-26T22:20:31Z [SERVER] INFO: Welcome to dockge!
dockge  | 2024-12-26T22:20:31Z [SERVER] INFO: NODE_ENV: production
dockge  | 2024-12-26T22:20:31Z [SERVER] INFO: Server Type: HTTP
dockge  | 2024-12-26T22:20:31Z [SERVER] INFO: Data Dir: ./data/
dockge  | 2024-12-26T22:20:31Z [DB] INFO: Database Type: sqlite
dockge  | 2024-12-26T22:20:31Z [SERVER] INFO: Connected to the database
dockge  | 2024-12-26T22:20:31Z [SERVER] INFO: Listening on 5001
dockge  | 2024-12-26T22:20:33Z [AUTH] INFO: Origin is not set, IP: ::ffff:192.168.1.154
dockge  | 2024-12-26T22:20:34Z [SERVER] INFO: Socket connected (direct)
dockge  | 2024-12-26T22:20:34Z [AUTH] INFO: Disabled Auth: auto login to admin
```
```
