### ISSUE TITLE
Can't delete stack if compose.yml has some error in it

### ISSUE THREAD

**Issue by Nostang3** [louislam/dockge#694]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

I started to create a stack but decided I didn't want it so I tried to delete it. Never deployed it. It wouldn't let me because it looks like it tries to validate the text before allowing me to delete it. It still had some <insert/path/here:/path/to/folder> entries. 

### 👟 Reproduction steps

1. Paste in some default compose

```
services:
  tinymediamanager:
    image: tinymediamanager/tinymediamanager:latest
    container_name: tinymediamanager
    environment:
      - USER_ID=1000
      - GROUP_ID=100
      - ALLOW_DIRECT_VNC=true
      - LC_ALL=en_US.UTF-8 # force UTF8
      - LANG=en_US.UTF-8   # force UTF8
      - PASSWORD=<password>
    volumes:
      - </path/to/local/data/>:/data
      - </path/to/movies>:/media/movies
      - </path/to/addons/>:/media/tv_shows
    ports:
      - 5900:5900 # VNC port
      - 4000:4000 # Webinterface
    restart: unless-stopped
```

2. Save.
3. Attempt to delete.

### 👀 Expected behavior

Would like to delete the file without having to check if the compose is valid. If I don't want to the stack it shouldn't need to be valid unless I'm missing something.

### 😓 Actual Behavior

Fails to delete with error.

### Dockge Version

1.4.2

### 💻 Operating System and Arch

Trunas Custom App

### 🌐 Browser

 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0

### 📝 Relevant log output

```shell
service "tinymediamanager" refers to undefined volume </path/to/local/data/>: invalid compose project
```

**Comment by christmaswreath** [comment]
Same issue here. "validating /opt/stacks/aio/compose.yaml: services.nextcloud-aio-mastercontainer.environment.0 must be a string"

**Comment by DomiiBunn** [comment]
As a simple solution. 

Remove the stacks folder

**Comment by christmaswreath** [comment]
You can also just replace the compose.yaml with a working one and then delete the stack. Still, it would be nice to be able to delete a “stack” with no compose.yaml and .env or one that doesn’t work.

**Comment by DomiiBunn** [comment]
@christmaswreath I agree.

Though this can cause an issue of hanging containers.

**Comment by F1zzyD** [comment]
Yep, having this issue as well. Can't delete it, change it, or anything if Dockage gets confused. It says it's maintaining it and inactive, but for some reason has no control over a stopped or ended container...

**Comment by jsox79** [comment]
can confirm this is still an issue

**Comment by christmaswreath** [comment]
> can confirm this is still an issue

fixed this by switching the compose file with the immich one (or any working one for that matter) and deleting the stack

```
services:
  mumble-server:
    image: mumblevoip/mumble-server:latest
    container_name: mumble-server
    hostname: mumble-server
    restart: on-failure
    ports:
      - 64738:64738
      - 64738:64738/udp
      - 6502:6502
    environment:
      - MUMBLE_SUPERUSER_PASSWORD=rsa3^zy9^ygmt43^VRD6F$ # not real password used anywhere
networks: {}
```
