### ISSUE TITLE
dockge lost single quotation when freshed

### ISSUE THREAD

**Issue by kbore** [louislam/dockge#709]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 👟 Reproduction steps

reproduce it with deploy  following yml in dockge. When press F5 refresh dockge web page, single quotation in environtment KEY is lost in web page.

```YML
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: 'nnnnnnnnnnnn'
```

### 👀 Expected behavior

Keep yml as I type:    

KEY: 'nnnnnnnnnnnn'

### 😓 Actual Behavior

Key value lost its single quotation     

KEY: 'nnnnnnnnnnnn'

### Dockge Version

1.4.2

### 💻 Operating System and Arch

debian11

### 🌐 Browser

chrome Version 131.0.6778.205
