### ISSUE TITLE
relative path not supported

### ISSUE THREAD

**Issue by foegra** [louislam/dockge#713]
### ⚠️ Please verify that this bug has NOT been reported before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### 👟 Reproduction steps

use local path for file volume mount that would look like this:
`./path/to/local/file.conf:/remote/mount`

### 👀 Expected behavior

success (it actually works with regular `docker compose up` )

### 😓 Actual Behavior

Cannot start stack. Error in log output

### Dockge Version

1.4.2

### 💻 Operating System and Arch

ubuntu 24.10

### 🌐 Browser

Firefox 134

### 🐋 Docker Version

27.5.0

### 📝 Relevant log output

```shell
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/opt/stacks/appflowy-cloud/nginx/nginx.conf" to rootfs at "/etc/nginx/nginx.conf": create mountpoint for /etc/nginx/nginx.conf mount: cannot create subdirectories in "/var/lib/docker/overlay2/4c4bec227f67450fb2e4ecb15198a7bc45dbc105adfd98382f6f32d589457a99/merged/etc/nginx/nginx.conf": not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

**Comment by DomiiBunn** [comment]
This error usually means that one of the paths does not exist.

Dockage does support relative mounts. Make sure that your file is indead in `/opt/stacks/<stack name>` as that is the path docker will be relating to.

**Comment by smith32843** [comment]
Dockage supports relative paths but the question is relative to what. The relative path in the compose file in the Dockage container is relative to the location of the stacks directory in the container - i.e., the value of the DOCKGE_STACKS_DIR environment variable. This path is passed to your Docker host docker daemon when Dockge does (the equivalent of) `docker compose up`. If the path doesn't exist on your Docker host, you get the file not found error.

I'm running Dockge on my Synology. I mapped my Synology stacks directory to the same name in the Dockge container and set DOCKGE_STACKS_DIR appropriately. I.e.,:

```
services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/dockge/data:/app/data
      - /volume1/docker/dockge/stacks:/volume1/docker/dockge/stacks
        
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/volume1/docker/dockge/stacks
 ``` 

After doing this, relative paths work as expected. The same thing should work on any other Docker environment.
