### ISSUE TITLE
configs.content syntax not supported despite being valid in Docker Compose 2.23.1+

### ISSUE THREAD

**Issue by MbMa** [louislam/dockge#727]
### ⚠️ Please verify that this bug has NOT been reported before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

## Description
When trying to use the new Docker Compose configs with inline `content` syntax (introduced in Docker Compose 2.23.1), Dockge validation fails with the error:
```validating /opt/stacks/qdrant/compose.yml: configs.qdrant_config Additional property content is not allowed```

This syntax is officially supported by Docker Compose 2.23.1+ and Docker Engine 25.0.0+ as documented here: https://docs.docker.com/compose/compose-file/07-configs/#configs-configuration-reference

## Example Configuration
Here's a minimal example that triggers the error:
```yaml
services:
  qdrant:
    image: qdrant/qdrant:latest
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml

configs:
  qdrant_config:
    content: |
      log_level: INFO
```
## Importance
This new syntax is particularly useful for keeping simple configurations inline without needing separate files. It would be great to have support for this feature in Dockge.

## Steps to Reproduce
1. Install Docker Engine ≥25.0.0 and Docker Compose ≥2.23.1
2. Create a new stack in Dockge
3. Create a compose.yml file with the following content:
```yaml
services:
  qdrant:
    image: qdrant/qdrant:latest
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml

configs:
  qdrant_config:
    content: |
      log_level: INFO
```
4. Try to save/update the stack in Dockge
5. Observe the validation error

## Verification
To verify this is a Dockge-specific issue:
1. Save the same compose.yml file locally
2. Run `docker compose up` from command line
3. The compose file works correctly when run directly with Docker Compose

### 👀 Expected behavior

Dockge should validate this as correct syntax since it's supported by recent Docker Compose versions.

### 😓 Actual Behavior

Validation fails with the error message about content not being an allowed property.

### Dockge Version

1.4.2

### 💻 Operating System and Arch

Ubuntu 20.04.6 aarch64

### 🌐 Browser

Firefox

### 🐋 Docker Version

Docker version 27.4.1, build b9d17ea, build b9d17ea / Docker Compose version v2.32.1

### 📝 Relevant log output

```shell

```
