### ISSUE TITLE
services.<name>.ports.<index>.app_protocol incorrectly blocked as not allowed

### ISSUE THREAD

**Issue by campfred** [louislam/dockge#733]
### ⚠️ Please verify that this bug has NOT been reported before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

Upon trying a compose manifest that had the long syntax implemented for exposing network ports, I came across a validation error.

This confused me as I was pretty sure I understood correctly [the docker compose documentation about this](https://docs.docker.com/reference/compose-file/services/#long-syntax-3).

So, I tried running my compose manifest with the actual `docker compose` command and it worked without complaints.

Then, when it was running, I switched back to Dockge to see if it would see it running and it was, but no logs could be seen as it was still complaining about the manifest being invalid.

### 👟 Reproduction steps

Try running the following manifest in Dockge.

```yaml
services:
  reverse-proxy:
    image: traefik:v3
    ports:
      - name: entrypoint-web
        target: 80
        published: 80
        app_protocol: http
      - name: entrypoint-websecure
        target: 443
        published: 443
        app_protocol: https
```

### 👀 Expected behavior

Dockge should run the compose manifest and start showing logs.

### 😓 Actual Behavior

Stack doesn’t start and an error is displayed instead.

```
validating /opt/stacks/traefik/compose.yaml  services.reverse-proxy.ports.0  Additional property app_protocol not allowed
```

### Dockge Version

1.4.2

### 💻 Operating System and Arch

Fedora 40

### 🌐 Browser

Safari iOS 18.3.1

### 🐋 Docker Version

Docker-CE 27.5.1

### 📝 Relevant log output

```shell

```
