### ISSUE TITLE
group_add with numeric IDs doesn't work

### ISSUE THREAD

**Issue by tomaskir** [louislam/dockge#738]
### ⚠️ Please verify that this bug has NOT been reported before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

Hello, it seems Dockge doesn't support number / integer declarations for `group_add` in the compose file.
```
group_add:
  - 999
```
This results in complete inability to use / see the entire stack.

Please see below for more info.

### 👟 Reproduction steps

Here is an example compose to reproduce:
```
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    user: 802:802
    group_add:
      - 999
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 127.0.0.1:8080:8080
```

### 👀 Expected behavior

This should work and not break Dockge :)

### 😓 Actual Behavior

In `Terminal`, an error can be seen:
```
1 error(s) decoding:

* 'group_add[0]' expected type 'string', got unconvertible type 'int', value: '999'
```

Containers have `N/A` state, `Bash` for container doesn't work, etc.

### Dockge Version

1.4.2

### 💻 Operating System and Arch

Ubuntu 22.04

### 🌐 Browser

Firefox

### 🐋 Docker Version

27.5.0

### 📝 Relevant log output

```shell

```
