### ISSUE TITLE
Dockage Can't See ".env" files

### ISSUE THREAD

**Issue by F1zzyD** [louislam/dockge#775]
### ⚠️ Please verify that this bug has NOT been reported before.

- [x] I checked and didn't find similar issue

### 🛡️ Security Policy

- [x] I agree to have read this project [Security Policy](https://github.com/louislam/dockge/security/policy)

### Description

It appears that Dockage is not able to see or read `.env` files correctly. Here's my setup:

dockage `compose.yaml`
```
services:
  dockge:
    container_name: dockage
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
        
      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      # âš ï¸ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # âš ï¸ 1. FULL path only. No relative path (MUST)
      # âš ï¸ 2. Left Stacks Path === Right Stacks Path (MUST)
      - ./opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/home/user/services/dockage/opt/stacks
```

Snippet from a container using an `.env`

```
services:
  web:
    container_name: test
    env_file:
      -  /home/user/services/web/.env
```

Yes, I want my `.env` file located in a specific directory. I've tried multiple ways of formatting it for Dockage to see, but every time I've gone to do `docker compose up` the container complains it can't see the file, even though I can open it, read it, and edit it.

### 👟 Reproduction steps

See above

### 👀 Expected behavior

It should work lol

### 😓 Actual Behavior

It don't work lol

### Dockge Version

1.5.0

### 💻 Operating System and Arch

Ubuntu 20.04

### 🌐 Browser

Firefox

### 📝 Relevant log output

```shell

```
